/** Curated Canadian municipalities by province/territory ISO code (ISO 3166-2:CA). */

export const CA_CITIES_BY_PROVINCE: Record<string, string[]> = {
  AB: [
    "Airdrie",
    "Brooks",
    "Calgary",
    "Camrose",
    "Canmore",
    "Chestermere",
    "Cold Lake",
    "Edmonton",
    "Fort McMurray",
    "Fort Saskatchewan",
    "Grande Prairie",
    "Leduc",
    "Lethbridge",
    "Lloydminster",
    "Medicine Hat",
    "Okotoks",
    "Red Deer",
    "Spruce Grove",
    "St. Albert",
    "Wetaskiwin",
  ],
  BC: [
    "Abbotsford",
    "Burnaby",
    "Chilliwack",
    "Coquitlam",
    "Delta",
    "Kamloops",
    "Kelowna",
    "Langley",
    "Maple Ridge",
    "Nanaimo",
    "New Westminster",
    "North Vancouver",
    "Port Coquitlam",
    "Port Moody",
    "Prince George",
    "Richmond",
    "Surrey",
    "Vancouver",
    "Victoria",
    "West Vancouver",
    "White Rock",
  ],
  MB: [
    "Brandon",
    "Dauphin",
    "Portage la Prairie",
    "Selkirk",
    "Steinbach",
    "Thompson",
    "Winkler",
    "Winnipeg",
  ],
  NB: [
    "Bathurst",
    "Dieppe",
    "Edmundston",
    "Fredericton",
    "Miramichi",
    "Moncton",
    "Saint John",
  ],
  NL: [
    "Conception Bay South",
    "Corner Brook",
    "Gander",
    "Mount Pearl",
    "Paradise",
    "St. John's",
  ],
  NS: [
    "Amherst",
    "Bridgewater",
    "Cape Breton",
    "Dartmouth",
    "Halifax",
    "Kentville",
    "New Glasgow",
    "Sydney",
    "Truro",
    "Yarmouth",
  ],
  NT: ["Fort Smith", "Hay River", "Inuvik", "Yellowknife"],
  NU: ["Iqaluit", "Rankin Inlet"],
  ON: [
    "Ajax",
    "Aurora",
    "Barrie",
    "Belleville",
    "Brampton",
    "Brantford",
    "Burlington",
    "Cambridge",
    "Chatham-Kent",
    "Clarington",
    "Cornwall",
    "East Gwillimbury",
    "Guelph",
    "Hamilton",
    "Kawartha Lakes",
    "Kingston",
    "Kitchener",
    "London",
    "Markham",
    "Milton",
    "Mississauga",
    "Newmarket",
    "Niagara Falls",
    "North Bay",
    "Oakville",
    "Oshawa",
    "Ottawa",
    "Peterborough",
    "Pickering",
    "Richmond Hill",
    "Sarnia",
    "Sault Ste. Marie",
    "St. Catharines",
    "St. Thomas",
    "Sudbury",
    "Thunder Bay",
    "Toronto",
    "Vaughan",
    "Waterloo",
    "Welland",
    "Whitby",
    "Windsor",
    "Woodstock",
  ],
  PE: ["Charlottetown", "Summerside"],
  QC: [
    "Brossard",
    "Châteauguay",
    "Drummondville",
    "Gatineau",
    "Granby",
    "Laval",
    "Lévis",
    "Longueuil",
    "Montreal",
    "Québec",
    "Repentigny",
    "Saguenay",
    "Saint-Jean-sur-Richelieu",
    "Saint-Jérôme",
    "Sherbrooke",
    "Terrebonne",
    "Trois-Rivières",
  ],
  SK: [
    "Estevan",
    "Lloydminster",
    "Moose Jaw",
    "North Battleford",
    "Prince Albert",
    "Regina",
    "Saskatoon",
    "Swift Current",
    "Yorkton",
  ],
  YT: ["Whitehorse"],
};

export function citiesForProvince(provinceCode: string): string[] {
  const code = (provinceCode || "").toUpperCase();
  return CA_CITIES_BY_PROVINCE[code] || [];
}

export function isKnownCity(provinceCode: string, city: string): boolean {
  const c = (city || "").trim();
  if (!c) return false;
  return citiesForProvince(provinceCode).some((x) => x.toLowerCase() === c.toLowerCase());
}

/** City options for a select, injecting a legacy value when not in the curated list. */
export function citySelectOptions(provinceCode: string, currentCity: string): string[] {
  const base = citiesForProvince(provinceCode);
  const cur = (currentCity || "").trim();
  if (!cur) return base;
  if (base.some((x) => x.toLowerCase() === cur.toLowerCase())) {
    // Prefer canonical casing from the list
    return base;
  }
  return [cur, ...base];
}
