/** Canadian municipalities by province/territory ISO code (ISO 3166-2:CA).
 *  Cities are the 2021 census subdivisions people put on an address, plus every
 *  name already in the picker (nothing removed).
 */

export const CA_CITIES_BY_PROVINCE: Record<string, string[]> = {
  AB: [
    "Acadia No. 34",
    "Acme",
    "Airdrie",
    "Alberta Beach",
    "Alix",
    "Alliance",
    "Amisk",
    "Andrew",
    "Argentia Beach",
    "Arrowwood",
    "Athabasca",
    "Athabasca County",
    "Banff",
    "Barnwell",
    "Barons",
    "Barrhead",
    "Barrhead County No. 11",
    "Bashaw",
    "Bassano",
    "Bawlf",
    "Beaumont",
    "Beaver County",
    "Beaverlodge",
    "Beiseker",
    "Bentley",
    "Berwyn",
    "Betula Beach",
    "Big Lakes County",
    "Big Valley",
    "Bighorn No. 8",
    "Birch Cove",
    "Birch Hills County",
    "Birchcliff",
    "Bittern Lake",
    "Black Diamond",
    "Blackfalds",
    "Bon Accord",
    "Bondiss",
    "Bonnyville",
    "Bonnyville Beach",
    "Bonnyville No. 87",
    "Bow Island",
    "Bowden",
    "Boyle",
    "Brazeau County",
    "Breton",
    "Brooks",
    "Bruderheim",
    "Burnstick Lake",
    "Calgary",
    "Calmar",
    "Camrose",
    "Camrose County",
    "Canmore",
    "Carbon",
    "Cardston",
    "Cardston County",
    "Carmangay",
    "Caroline",
    "Carstairs",
    "Castle Island",
    "Castor",
    "Champion",
    "Chauvin",
    "Chestermere",
    "Chipman",
    "Claresholm",
    "Clear Hills",
    "Clearwater County",
    "Clive",
    "Clyde",
    "Coaldale",
    "Coalhurst",
    "Cochrane",
    "Cold Lake",
    "Consort",
    "Coronation",
    "Coutts",
    "Cowley",
    "Cremona",
    "Crossfield",
    "Crowsnest Pass",
    "Crystal Springs",
    "Cypress County",
    "Czar",
    "Daysland",
    "Delburne",
    "Delia",
    "Devon",
    "Didsbury",
    "Donalda",
    "Donnelly",
    "Drayton Valley",
    "Drumheller",
    "Duchess",
    "Eckville",
    "Edberg",
    "Edgerton",
    "Edmonton",
    "Edson",
    "Elk Point",
    "Elnora",
    "Empress",
    "Fairview",
    "Fairview No. 136",
    "Falher",
    "Flagstaff County",
    "Foothills County",
    "Foremost",
    "Forestburg",
    "Fort Macleod",
    "Fort McMurray",
    "Fort Saskatchewan",
    "Forty Mile County No. 8",
    "Fox Creek",
    "Ghost Lake",
    "Gibbons",
    "Girouxville",
    "Glendon",
    "Glenwood",
    "Golden Days",
    "Grande Prairie",
    "Grande Prairie County No. 1",
    "Grandview",
    "Greenview No. 16",
    "Grimshaw",
    "Gull Lake",
    "Half Moon Bay",
    "Halkirk",
    "Hanna",
    "Hardisty",
    "Hay Lakes",
    "Heisler",
    "High Level",
    "High Prairie",
    "High River",
    "Hill Spring",
    "Hines Creek",
    "Hinton",
    "Holden",
    "Horseshoe Bay",
    "Hughenden",
    "Hussar",
    "Hythe",
    "Improvement District No. 12 Jasper Park",
    "Improvement District No. 13 Elk Island",
    "Improvement District No. 24 Wood Buffalo",
    "Improvement District No. 25 Willmore Wilderness",
    "Improvement District No. 349",
    "Improvement District No. 4 Waterton",
    "Improvement District No. 9 Banff",
    "Innisfail",
    "Innisfree",
    "Irma",
    "Irricana",
    "Island Lake",
    "Island Lake South",
    "Itaska Beach",
    "Jarvis Bay",
    "Jasper",
    "Kananaskis",
    "Kapasiwin",
    "Killam",
    "Kitscoty",
    "Kneehill County",
    "Lac la Biche County",
    "Lac Ste. Anne County",
    "Lacombe",
    "Lacombe County",
    "Lakeview",
    "Lamont",
    "Lamont County",
    "Larkspur",
    "Leduc",
    "Leduc County",
    "Legal",
    "Lesser Slave River No. 124",
    "Lethbridge",
    "Lethbridge County",
    "Linden",
    "Lloydminster",
    "Lomond",
    "Longview",
    "Lougheed",
    "Ma-Me-O Beach",
    "Mackenzie County",
    "Magrath",
    "Manning",
    "Mannville",
    "Marwayne",
    "Mayerthorpe",
    "McLennan",
    "Medicine Hat",
    "Mewatha Beach",
    "Milk River",
    "Millet",
    "Milo",
    "Minburn County No. 27",
    "Morinville",
    "Morrin",
    "Mountain View County",
    "Mundare",
    "Munson",
    "Myrnam",
    "Nakamun Park",
    "Nampa",
    "Nanton",
    "Newell County",
    "Nobleford",
    "Norglenwold",
    "Norris Beach",
    "Northern Lights County",
    "Northern Sunrise County",
    "Okotoks",
    "Olds",
    "Onoway",
    "Opportunity No. 17",
    "Oyen",
    "Paintearth County No. 18",
    "Paradise Valley",
    "Parkland Beach",
    "Parkland County",
    "Peace No. 135",
    "Peace River",
    "Pelican Narrows",
    "Penhold",
    "Picture Butte",
    "Pincher Creek",
    "Pincher Creek No. 9",
    "Point Alison",
    "Ponoka",
    "Ponoka County",
    "Poplar Bay",
    "Provost",
    "Provost No. 52",
    "Rainbow Lake",
    "Ranchland No. 66",
    "Raymond",
    "Red Deer",
    "Red Deer County",
    "Redcliff",
    "Redwater",
    "Rimbey",
    "Rochon Sands",
    "Rocky Mountain House",
    "Rocky View County",
    "Rockyford",
    "Rosalind",
    "Rosemary",
    "Ross Haven",
    "Rycroft",
    "Ryley",
    "Saddle Hills County",
    "Sandy Beach",
    "Seba Beach",
    "Sedgewick",
    "Sexsmith",
    "Silver Beach",
    "Silver Sands",
    "Slave Lake",
    "Smoky Lake",
    "Smoky Lake County",
    "Smoky River No. 130",
    "South Baptiste",
    "South View",
    "Special Area No. 2",
    "Special Area No. 3",
    "Special Area No. 4",
    "Spirit River",
    "Spirit River No. 133",
    "Spring Lake",
    "Spruce Grove",
    "St. Albert",
    "St. Paul",
    "St. Paul County No. 19",
    "Standard",
    "Starland County",
    "Stavely",
    "Stettler",
    "Stettler County No. 6",
    "Stirling",
    "Stony Plain",
    "Strathcona County",
    "Strathmore",
    "Sturgeon County",
    "Sunbreaker Cove",
    "Sundance Beach",
    "Sundre",
    "Sunrise Beach",
    "Sunset Beach",
    "Sunset Point",
    "Swan Hills",
    "Sylvan Lake",
    "Taber",
    "Thorhild County",
    "Thorsby",
    "Three Hills",
    "Tofield",
    "Trochu",
    "Turner Valley",
    "Two Hills",
    "Two Hills County No. 21",
    "Val Quentin",
    "Valleyview",
    "Vauxhall",
    "Vegreville",
    "Vermilion",
    "Vermilion River County",
    "Veteran",
    "Viking",
    "Vilna",
    "Vulcan",
    "Vulcan County",
    "Wainwright",
    "Wainwright No. 61",
    "Waiparous",
    "Warburg",
    "Warner",
    "Warner County No. 5",
    "Waskatenau",
    "Wembley",
    "West Baptiste",
    "West Cove",
    "Westlock",
    "Westlock County",
    "Wetaskiwin",
    "Wetaskiwin County No. 10",
    "Wheatland County",
    "Whispering Hills",
    "White Sands",
    "Whitecourt",
    "Willow Creek No. 26",
    "Wood Buffalo",
    "Woodlands County",
    "Yellowhead County",
    "Yellowstone",
    "Youngstown",
  ],
  BC: [
    "Abbotsford",
    "Alert Bay",
    "Anmore",
    "Armstrong",
    "Ashcroft",
    "Barriere",
    "Belcarra",
    "Bowen Island",
    "Burnaby",
    "Burns Lake",
    "Cache Creek",
    "Campbell River",
    "Canal Flats",
    "Castlegar",
    "Central Saanich",
    "Chase",
    "Chetwynd",
    "Chilliwack",
    "Clearwater",
    "Clinton",
    "Coldstream",
    "Colwood",
    "Comox",
    "Coquitlam",
    "Courtenay",
    "Cranbrook",
    "Creston",
    "Cumberland",
    "Dawson Creek",
    "Delta",
    "Duncan",
    "Elkford",
    "Enderby",
    "Esquimalt",
    "Fernie",
    "Fort St. James",
    "Fort St. John",
    "Fraser Lake",
    "Fruitvale",
    "Gibsons",
    "Gold River",
    "Golden",
    "Grand Forks",
    "Granisle",
    "Greenwood",
    "Harrison Hot Springs",
    "Hazelton",
    "Highlands",
    "Hope",
    "Houston",
    "Hudson's Hope",
    "Invermere",
    "Kamloops",
    "Kaslo",
    "Kelowna",
    "Kent",
    "Keremeos",
    "Kimberley",
    "Kitimat",
    "Ladysmith",
    "Lake Country",
    "Lake Cowichan",
    "Langford",
    "Langley",
    "Lantzville",
    "Lillooet",
    "Lions Bay",
    "Logan Lake",
    "Lumby",
    "Lytton",
    "Mackenzie",
    "Maple Ridge",
    "Masset",
    "McBride",
    "Merritt",
    "Metchosin",
    "Midway",
    "Mission",
    "Montrose",
    "Nakusp",
    "Nanaimo",
    "Nelson",
    "New Denver",
    "New Hazelton",
    "New Westminster",
    "North Cowichan",
    "North Saanich",
    "North Vancouver",
    "Northern Rockies",
    "Oak Bay",
    "Oliver",
    "One Hundred Mile House",
    "Osoyoos",
    "Parksville",
    "Peachland",
    "Pemberton",
    "Penticton",
    "Pitt Meadows",
    "Port Alberni",
    "Port Alice",
    "Port Clements",
    "Port Coquitlam",
    "Port Edward",
    "Port Hardy",
    "Port McNeill",
    "Port Moody",
    "Pouce Coupe",
    "Powell River",
    "Prince George",
    "Prince Rupert",
    "Princeton",
    "Qualicum Beach",
    "Queen Charlotte",
    "Quesnel",
    "Radium Hot Springs",
    "Revelstoke",
    "Richmond",
    "Rossland",
    "Saanich",
    "Salmo",
    "Salmon Arm",
    "Sayward",
    "Sechelt",
    "Sicamous",
    "Sidney",
    "Silverton",
    "Slocan",
    "Smithers",
    "Sooke",
    "Spallumcheen",
    "Sparwood",
    "Squamish",
    "Stewart",
    "Summerland",
    "Sun Peaks Mountain",
    "Surrey",
    "Tahsis",
    "Taylor",
    "Telkwa",
    "Terrace",
    "Tofino",
    "Trail",
    "Tumbler Ridge",
    "Ucluelet",
    "Valemount",
    "Vancouver",
    "Vanderhoof",
    "Vernon",
    "Victoria",
    "View Royal",
    "Warfield",
    "Wells",
    "West Kelowna",
    "West Vancouver",
    "Whistler",
    "White Rock",
    "Williams Lake",
    "Zeballos",
  ],
  MB: [
    "Alexander",
    "Alonsa",
    "Altona",
    "Arborg",
    "Argyle",
    "Armstrong",
    "Beausejour",
    "Bifrost-Riverton",
    "Boissevain-Morton",
    "Brandon",
    "Brenda-Waskada",
    "Brokenhead",
    "Carberry",
    "Carman",
    "Cartier",
    "Cartwright-Roblin",
    "Churchill",
    "Clanwilliam-Erickson",
    "Coldwell",
    "Cornwallis",
    "Dauphin",
    "De Salaberry",
    "Deloraine-Winchester",
    "Dufferin",
    "Dunnottar",
    "East St. Paul",
    "Ellice-Archie",
    "Elton",
    "Emerson-Franklin",
    "Ethelbert",
    "Fisher",
    "Flin Flon",
    "Gilbert Plains",
    "Gillam",
    "Gimli",
    "Glenboro-South Cypress",
    "Glenella-Lansdowne",
    "Grahamdale",
    "Grand Rapids",
    "Grandview",
    "Grassland",
    "Grey",
    "Hamiota",
    "Hanover",
    "Harrison Park",
    "Headingley",
    "Hillsburg-Roblin-Shell River",
    "Kelsey",
    "Killarney - Turtle Mountain",
    "La Broquerie",
    "Lac du Bonnet",
    "Lakeshore",
    "Leaf Rapids",
    "Lorne",
    "Louise",
    "Lynn Lake",
    "Macdonald",
    "McCreary",
    "Melita",
    "Minitonas-Bowsman",
    "Minnedosa",
    "Minto-Odanah",
    "Montcalm",
    "Morden",
    "Morris",
    "Mossey River",
    "Mountain (North)",
    "Mountain (South)",
    "Mystery Lake",
    "Neepawa",
    "Niverville",
    "Norfolk-Treherne",
    "North Cypress-Langford",
    "North Norfolk",
    "Oakland-Wawanesa",
    "Oakview",
    "Pembina",
    "Pinawa",
    "Piney",
    "Pipestone",
    "Portage la Prairie",
    "Powerview-Pine Falls",
    "Prairie Lakes",
    "Prairie View",
    "Reynolds",
    "Rhineland",
    "Riding Mountain West",
    "Ritchot",
    "Riverdale",
    "Rockwood",
    "Roland",
    "Rosedale",
    "Rossburn",
    "Rosser",
    "Russell-Binscarth",
    "Selkirk",
    "Sifton",
    "Snow Lake",
    "Souris-Glenwood",
    "Springfield",
    "St-Pierre-Jolys",
    "St. Andrews",
    "St. Clements",
    "St. François Xavier",
    "St. Laurent",
    "Stanley",
    "Ste. Anne",
    "Ste. Rose",
    "Steinbach",
    "Stonewall",
    "Stuartburn",
    "Swan River",
    "Swan Valley West",
    "Taché",
    "Teulon",
    "The Pas",
    "Thompson",
    "Two Borders",
    "Victoria",
    "Victoria Beach",
    "Virden",
    "Wallace-Woodworth",
    "West Interlake",
    "West St. Paul",
    "WestLake-Gladstone",
    "Whitehead",
    "Whitemouth",
    "Winkler",
    "Winnipeg",
    "Winnipeg Beach",
    "Woodlands",
    "Yellowhead",
  ],
  NB: [
    "Aberdeen",
    "Acadieville",
    "Addington",
    "Allardville",
    "Alma",
    "Alnwick",
    "Andover",
    "Aroostook",
    "Atholville",
    "Balmoral",
    "Bas-Caraquet",
    "Bath",
    "Bathurst",
    "Beaubassin East",
    "Belledune",
    "Beresford",
    "Bertrand",
    "Blacks Harbour",
    "Blackville",
    "Blissfield",
    "Blissville",
    "Botsford",
    "Bouctouche",
    "Bright",
    "Brighton",
    "Brunswick",
    "Burton",
    "Cambridge",
    "Cambridge-Narrows",
    "Campbellton",
    "Campobello Island",
    "Canning",
    "Canterbury",
    "Cap-Pelé",
    "Caraquet",
    "Cardwell",
    "Carleton",
    "Centreville",
    "Charlo",
    "Chatham",
    "Chipman",
    "Clarendon",
    "Cocagne",
    "Colborne",
    "Coverdale",
    "Dalhousie",
    "Denmark",
    "Derby",
    "Dieppe",
    "Doaktown",
    "Dorchester",
    "Douglas",
    "Drummond",
    "Dufferin",
    "Dumbarton",
    "Dumfries",
    "Dundas",
    "Durham",
    "Edmundston",
    "Eel River Crossing",
    "Eldon",
    "Elgin",
    "Florenceville-Bristol",
    "Fredericton",
    "Fredericton Junction",
    "Gagetown",
    "Gladstone",
    "Glenelg",
    "Gordon",
    "Grand Bay-Westfield",
    "Grand Falls",
    "Grand Manan",
    "Grande-Anse",
    "Greenwich",
    "Hammond",
    "Hampstead",
    "Hampton",
    "Hanwell",
    "Harcourt",
    "Hardwicke",
    "Hartland",
    "Harvey",
    "Haut-Madawaska",
    "Havelock",
    "Hillsborough",
    "Hopewell",
    "Huskisson",
    "Inkerman",
    "Johnston",
    "Kars",
    "Kedgwick",
    "Kent",
    "Kingsclear",
    "Kingston",
    "Lac Baker",
    "Lamèque",
    "Le Goulet",
    "Lepreau",
    "Lincoln",
    "Lorne",
    "Madawaska",
    "Maisonnette",
    "Manners Sutton",
    "Maugerville",
    "McAdam",
    "Meductic",
    "Memramcook",
    "Millville",
    "Minto",
    "Miramichi",
    "Moncton",
    "Musquash",
    "Nackawic",
    "Neguac",
    "Nelson",
    "New Bandon",
    "New Maryland",
    "Newcastle",
    "Nigadoo",
    "North Lake",
    "Northampton",
    "Northesk",
    "Northfield",
    "Norton",
    "Notre-Dame-de-Lourdes",
    "Oromocto",
    "Paquetville",
    "Peel",
    "Pennfield",
    "Perth",
    "Perth-Andover",
    "Petersville",
    "Petit-Rocher",
    "Petitcodiac",
    "Plaster Rock",
    "Pointe-Verte",
    "Port Elgin",
    "Prince William",
    "Queensbury",
    "Quispamsis",
    "Rexton",
    "Richibucto",
    "Richmond",
    "Riverside-Albert",
    "Riverview",
    "Rivière-Verte",
    "Rogersville",
    "Rothesay",
    "Sackville",
    "Saint Andrews",
    "Saint Croix",
    "Saint David",
    "Saint George",
    "Saint James",
    "Saint John",
    "Saint Martins",
    "Saint Mary",
    "Saint Marys",
    "Saint Patrick",
    "Saint Stephen",
    "Saint-André",
    "Saint-Antoine",
    "Saint-Basile",
    "Saint-Charles",
    "Saint-Isidore",
    "Saint-Jacques",
    "Saint-Joseph",
    "Saint-Louis",
    "Saint-Louis de Kent",
    "Saint-Léolin",
    "Saint-Léonard",
    "Saint-Paul",
    "Saint-Quentin",
    "Sainte-Anne",
    "Sainte-Anne-de-Madawaska",
    "Sainte-Marie-Saint-Raphaël",
    "Salisbury",
    "Shediac",
    "Sheffield",
    "Shippagan",
    "Simonds",
    "Southampton",
    "Southesk",
    "Springfield",
    "St. George",
    "St. Martins",
    "St. Stephen",
    "Stanley",
    "Studholm",
    "Sussex",
    "Sussex Corner",
    "Tide Head",
    "Tracadie",
    "Tracy",
    "Upham",
    "Upper Miramichi",
    "Wakefield",
    "Waterborough",
    "Waterford",
    "Weldford",
    "Wellington",
    "West Isles",
    "Westfield",
    "Westmorland",
    "Wickham",
    "Wicklow",
    "Wilmot",
    "Woodstock",
  ],
  NL: [
    "Admirals Beach",
    "Anchor Point",
    "Appleton",
    "Aquaforte",
    "Arnold's Cove",
    "Avondale",
    "Badger",
    "Baie Verte",
    "Baine Harbour",
    "Bauline",
    "Bay Bulls",
    "Bay de Verde",
    "Bay L'Argent",
    "Bay Roberts",
    "Baytona",
    "Beachside",
    "Bellburns",
    "Belleoram",
    "Birchy Bay",
    "Bird Cove",
    "Bishop's Cove",
    "Bishop's Falls",
    "Bonavista",
    "Botwood",
    "Branch",
    "Brent's Cove",
    "Brighton",
    "Brigus",
    "Bryant's Cove",
    "Buchans",
    "Burgeo",
    "Burin",
    "Burlington",
    "Burnt Islands",
    "Campbellton",
    "Cape Broyle",
    "Cape St. George",
    "Carbonear",
    "Carmanville",
    "Cartwright, Labrador",
    "Centreville-Wareham-Trinity",
    "Chance Cove",
    "Change Islands",
    "Channel-Port aux Basques",
    "Chapel Arm",
    "Charlottetown (Labrador)",
    "Clarenville",
    "Clarke's Beach",
    "Coachman's Cove",
    "Colinet",
    "Colliers",
    "Come By Chance",
    "Comfort Cove-Newstead",
    "Conception Bay South",
    "Conception Harbour",
    "Conche",
    "Cook's Harbour",
    "Cormack",
    "Corner Brook",
    "Cottlesville",
    "Cow Head",
    "Cox's Cove",
    "Crow Head",
    "Cupids",
    "Daniel's Harbour",
    "Deer Lake",
    "Dover",
    "Duntara",
    "Eastport",
    "Elliston",
    "Embree",
    "Englee",
    "English Harbour East",
    "Fermeuse",
    "Ferryland",
    "Flatrock",
    "Fleur de Lys",
    "Flower's Cove",
    "Fogo Island",
    "Forteau",
    "Fortune",
    "Fox Cove-Mortier",
    "Fox Harbour",
    "Frenchman's Cove",
    "Gallants",
    "Gambo",
    "Gander",
    "Garnish",
    "Gaskiers-Point La Haye",
    "Gaultois",
    "Gillams",
    "Glenburnie-Birchy Head-Shoal Brook",
    "Glenwood",
    "Glovertown",
    "Goose Cove East",
    "Grand Bank",
    "Grand Falls-Windsor",
    "Grand Le Pierre",
    "Greenspond",
    "Hampden",
    "Hant's Harbour",
    "Happy Adventure",
    "Happy Valley-Goose Bay",
    "Harbour Breton",
    "Harbour Grace",
    "Harbour Main-Chapel's Cove-Lakeview",
    "Hare Bay",
    "Hawke's Bay",
    "Heart's Content",
    "Heart's Delight-Islington",
    "Heart's Desire",
    "Hermitage-Sandyville",
    "Holyrood",
    "Hopedale",
    "Howley",
    "Hughes Brook",
    "Humber Arm South",
    "Indian Bay",
    "Irishtown-Summerside",
    "Isle aux Morts",
    "Jackson's Arm",
    "Keels",
    "King's Cove",
    "King's Point",
    "Kippens",
    "L'Anse au Loup",
    "L'Anse-au-Clair",
    "Labrador City",
    "Lamaline",
    "Lark Harbour",
    "LaScie",
    "Lawn",
    "Leading Tickles",
    "Lewin's Cove",
    "Lewisporte",
    "Little Bay",
    "Little Bay East",
    "Little Bay Islands",
    "Little Burnt Bay",
    "Logy Bay-Middle Cove-Outer Cove",
    "Long Harbour-Mount Arlington Heights",
    "Lord's Cove",
    "Lourdes",
    "Lumsden",
    "Lushes Bight-Beaumont-Beaumont North",
    "Main Brook",
    "Makkovik",
    "Mary's Harbour",
    "Marystown",
    "Massey Drive",
    "McIvers",
    "Meadows",
    "Middle Arm",
    "Miles Cove",
    "Millertown",
    "Milltown-Head of Bay d'Espoir",
    "Ming's Bight",
    "Morrisville",
    "Mount Carmel-Mitchells Brook-St. Catherine's",
    "Mount Moriah",
    "Mount Pearl",
    "Musgrave Harbour",
    "Musgravetown",
    "Nain",
    "New Perlican",
    "New-Wes-Valley",
    "Nippers Harbour",
    "Norman's Cove-Long Cove",
    "Norris Arm",
    "Norris Point",
    "North River",
    "North West River",
    "Northern Arm",
    "Old Perlican",
    "Pacquet",
    "Paradise",
    "Parkers Cove",
    "Parson's Pond",
    "Pasadena",
    "Peterview",
    "Petty Harbour-Maddox Cove",
    "Pilley's Island",
    "Pinware",
    "Placentia",
    "Point au Gaul",
    "Point Lance",
    "Point Leamington",
    "Point May",
    "Point of Bay",
    "Pool's Cove",
    "Port Anson",
    "Port au Choix",
    "Port au Port East",
    "Port au Port West-Aguathuna-Felix Cove",
    "Port Blandford",
    "Port Hope Simpson",
    "Port Kirwan",
    "Port Rexton",
    "Port Saunders",
    "Portugal Cove South",
    "Portugal Cove-St. Philip's",
    "Postville",
    "Pouch Cove",
    "Raleigh",
    "Ramea",
    "Red Bay",
    "Red Harbour",
    "Reidville",
    "Rencontre East",
    "Renews-Cappahayden",
    "Rigolet",
    "River of Ponds",
    "Riverhead",
    "Robert's Arm",
    "Rocky Harbour",
    "Roddickton-Bide Arm",
    "Rose Blanche-Harbour le Cou",
    "Rushoon",
    "Sally's Cove",
    "Salmon Cove",
    "Salvage",
    "Sandringham",
    "Sandy Cove",
    "Seal Cove (Fortune Bay)",
    "Seal Cove (White Bay)",
    "Small Point-Adam's Cove-Blackhead-Broad Cove",
    "South Brook",
    "South River",
    "Southern Harbour",
    "Spaniard's Bay",
    "Springdale",
    "St. Alban's",
    "St. Anthony",
    "St. Bernard's-Jacques Fontaine",
    "St. Brendan's",
    "St. Bride's",
    "St. George's",
    "St. Jacques-Coomb's Cove",
    "St. John's",
    "St. Joseph's",
    "St. Lawrence",
    "St. Lewis",
    "St. Lunaire-Griquet",
    "St. Mary's",
    "St. Pauls",
    "St. Shott's",
    "St. Vincent's-St. Stephen's-Peter's River",
    "Steady Brook",
    "Stephenville",
    "Stephenville Crossing",
    "Summerford",
    "Sunnyside",
    "Terra Nova",
    "Terrenceville",
    "Tilt Cove",
    "Torbay",
    "Traytown",
    "Trepassey",
    "Trinity (Trinity Bay)",
    "Trinity Bay North",
    "Triton",
    "Trout River",
    "Twillingate",
    "Upper Island Cove",
    "Victoria",
    "Wabana",
    "Wabush",
    "West St. Modeste",
    "Westport",
    "Whitbourne",
    "Whiteway",
    "Winterland",
    "Winterton",
    "Witless Bay",
    "Woodstock",
    "Woody Point, Bonne Bay",
    "York Harbour",
  ],
  NS: [
    "Amherst",
    "Annapolis Royal",
    "Annapolis, Subd. A",
    "Annapolis, Subd. B",
    "Annapolis, Subd. C",
    "Annapolis, Subd. D",
    "Antigonish",
    "Antigonish, Subd. A",
    "Antigonish, Subd. B",
    "Argyle",
    "Barrington",
    "Berwick",
    "Bridgewater",
    "Cape Breton",
    "Chester",
    "Clare",
    "Clark's Harbour",
    "Colchester, Subd. A",
    "Colchester, Subd. B",
    "Colchester, Subd. C",
    "Cumberland, Subd. A",
    "Cumberland, Subd. B",
    "Cumberland, Subd. C",
    "Cumberland, Subd. D",
    "Dartmouth",
    "Digby",
    "East Hants",
    "Guysborough",
    "Halifax",
    "Inverness, Subd. A",
    "Inverness, Subd. B",
    "Inverness, Subd. C",
    "Kentville",
    "Kings, Subd. A",
    "Kings, Subd. B",
    "Kings, Subd. C",
    "Kings, Subd. D",
    "Lockeport",
    "Lunenburg",
    "Mahone Bay",
    "Middleton",
    "Mulgrave",
    "New Glasgow",
    "Oxford",
    "Pictou",
    "Pictou, Subd. A",
    "Pictou, Subd. B",
    "Pictou, Subd. C",
    "Port Hawkesbury",
    "Queens",
    "Richmond, Subd. A",
    "Richmond, Subd. B",
    "Richmond, Subd. C",
    "Shelburne",
    "St. Mary's",
    "Stellarton",
    "Stewiacke",
    "Sydney",
    "Trenton",
    "Truro",
    "Victoria, Subd. A",
    "Victoria, Subd. B",
    "West Hants",
    "Westville",
    "Wolfville",
    "Yarmouth",
  ],
  NT: [
    "Aklavik",
    "Behchokò",
    "Colville Lake",
    "Dettah",
    "Déline",
    "Enterprise",
    "Fort Good Hope",
    "Fort Liard",
    "Fort McPherson",
    "Fort Providence",
    "Fort Resolution",
    "Fort Simpson",
    "Fort Smith",
    "Gamètì",
    "Hay River",
    "Inuvik",
    "Jean Marie River",
    "Kakisa",
    "Lutselk'e",
    "Nahanni Butte",
    "Norman Wells",
    "Paulatuk",
    "Reliance",
    "Sachs Harbour",
    "Sambaa K’e",
    "Tsiigehtchic",
    "Tuktoyaktuk",
    "Tulita",
    "Ulukhaktok",
    "Wekweètì",
    "Whatì",
    "Wrigley",
    "Yellowknife",
  ],
  NU: [
    "Arctic Bay",
    "Arviat",
    "Baker Lake",
    "Bathurst Inlet",
    "Cambridge Bay",
    "Cape Dorset",
    "Chesterfield Inlet",
    "Clyde River",
    "Coral Harbour",
    "Gjoa Haven",
    "Grise Fiord",
    "Hall Beach",
    "Igloolik",
    "Iqaluit",
    "Kimmirut",
    "Kugaaruk",
    "Kugluktuk",
    "Nanisivik",
    "Naujaat",
    "Pangnirtung",
    "Pond Inlet",
    "Qikiqtarjuaq",
    "Rankin Inlet",
    "Resolute",
    "Sanikiluaq",
    "Taloyoak",
    "Umingmaktok",
    "Whale Cove",
  ],
  ON: [
    "Addington Highlands",
    "Adelaide-Metcalfe",
    "Adjala-Tosorontio",
    "Admaston/Bromley",
    "Ajax",
    "Alberton",
    "Alfred and Plantagenet",
    "Algonquin Highlands",
    "Alnwick/Haldimand",
    "Amaranth",
    "Amherstburg",
    "Armour",
    "Armstrong",
    "Arnprior",
    "Arran-Elderslie",
    "Ashfield-Colborne-Wawanosh",
    "Asphodel-Norwood",
    "Assiginack",
    "Athens",
    "Atikokan",
    "Augusta",
    "Aurora",
    "Aylmer",
    "Baldwin",
    "Bancroft",
    "Barrie",
    "Bayham",
    "Beckwith",
    "Belleville",
    "Billings",
    "Black River-Matheson",
    "Blandford-Blenheim",
    "Blind River",
    "Bluewater",
    "Bonfield",
    "Bonnechere Valley",
    "Bracebridge",
    "Bradford West Gwillimbury",
    "Brampton",
    "Brant",
    "Brant County",
    "Brantford",
    "Brethour",
    "Brighton",
    "Brock",
    "Brockton",
    "Brockville",
    "Brooke-Alvinston",
    "Bruce Mines",
    "Brudenell, Lyndoch and Raglan",
    "Burk's Falls",
    "Burlington",
    "Burpee and Mills",
    "Caledon",
    "Callander",
    "Calvin",
    "Cambridge",
    "Carleton Place",
    "Carling",
    "Carlow/Mayo",
    "Casey",
    "Casselman",
    "Cavan Monaghan",
    "Central Elgin",
    "Central Frontenac",
    "Central Huron",
    "Central Manitoulin",
    "Centre Hastings",
    "Centre Wellington",
    "Chamberlain",
    "Champlain",
    "Chapleau",
    "Chapple",
    "Charlton and Dack",
    "Chatham-Kent",
    "Chatsworth",
    "Chisholm",
    "Clarence-Rockland",
    "Clarington",
    "Clearview",
    "Cobalt",
    "Cobourg",
    "Cochrane",
    "Cockburn Island",
    "Coleman",
    "Collingwood",
    "Conmee",
    "Cornwall",
    "Cramahe",
    "Dawn-Euphemia",
    "Dawson",
    "Deep River",
    "Deseronto",
    "Dorion",
    "Douro-Dummer",
    "Drummond/North Elmsley",
    "Dryden",
    "Dubreuilville",
    "Dutton/Dunwich",
    "Dysart et al",
    "Ear Falls",
    "East Ferris",
    "East Garafraxa",
    "East Gwillimbury",
    "East Hawkesbury",
    "East Zorra-Tavistock",
    "Edwardsburgh/Cardinal",
    "Elizabethtown-Kitley",
    "Elliot Lake",
    "Emo",
    "Englehart",
    "Enniskillen",
    "Erin",
    "Espanola",
    "Essa",
    "Essex",
    "Etobicoke",
    "Evanturel",
    "Faraday",
    "Fauquier-Strickland",
    "Fort Erie",
    "Fort Frances",
    "French River",
    "Front of Yonge",
    "Frontenac Islands",
    "Gananoque",
    "Gauthier",
    "Georgian Bay",
    "Georgian Bluffs",
    "Georgina",
    "Gillies",
    "Goderich",
    "Gordon/Barrie Island",
    "Gore Bay",
    "Grand Valley",
    "Gravenhurst",
    "Greater Madawaska",
    "Greater Napanee",
    "Greater Sudbury",
    "Greenstone",
    "Grey Highlands",
    "Grimsby",
    "Guelph",
    "Guelph/Eramosa",
    "Haldimand County",
    "Halton Hills",
    "Hamilton",
    "Hamilton Township",
    "Hanover",
    "Harley",
    "Harris",
    "Hastings Highlands",
    "Havelock-Belmont-Methuen",
    "Hawkesbury",
    "Head, Clara and Maria",
    "Hearst",
    "Highlands East",
    "Hilliard",
    "Hilton",
    "Hilton Beach",
    "Hornepayne",
    "Horton",
    "Howick",
    "Hudson",
    "Huntsville",
    "Huron East",
    "Huron Shores",
    "Huron-Kinloss",
    "Ignace",
    "Ingersoll",
    "Innisfil",
    "Iroquois Falls",
    "James",
    "Jocelyn",
    "Johnson",
    "Joly",
    "Kapuskasing",
    "Kawartha Lakes",
    "Kearney",
    "Kenora",
    "Kerns",
    "Killaloe, Hagarty and Richards",
    "Killarney",
    "Kincardine",
    "King",
    "Kingston",
    "Kingsville",
    "Kirkland Lake",
    "Kitchener",
    "La Vallee",
    "Laird",
    "Lake of Bays",
    "Lake of the Woods",
    "Lakeshore",
    "Lambton Shores",
    "Lanark Highlands",
    "Larder Lake",
    "LaSalle",
    "Latchford",
    "Laurentian Hills",
    "Laurentian Valley",
    "Leamington",
    "Leeds and the Thousand Islands",
    "Limerick",
    "Lincoln",
    "London",
    "Loyalist",
    "Lucan Biddulph",
    "Macdonald, Meredith and Aberdeen Additional",
    "Machar",
    "Machin",
    "Madawaska Valley",
    "Madoc",
    "Magnetawan",
    "Malahide",
    "Manitouwadge",
    "Mapleton",
    "Marathon",
    "Markham",
    "Markstay-Warren",
    "Marmora and Lake",
    "Matachewan",
    "Mattawa",
    "Mattawan",
    "Mattice-Val Côté",
    "McDougall",
    "McGarry",
    "McKellar",
    "McMurrich/Monteith",
    "McNab/Braeside",
    "Meaford",
    "Melancthon",
    "Merrickville-Wolford",
    "Middlesex Centre",
    "Midland",
    "Milton",
    "Minden Hills",
    "Minto",
    "Mississauga",
    "Mississippi Mills",
    "Mono",
    "Montague",
    "Moonbeam",
    "Moosonee",
    "Morley",
    "Morris-Turnberry",
    "Mulmur",
    "Muskoka Lakes",
    "Nairn and Hyman",
    "Neebing",
    "New Tecumseth",
    "Newbury",
    "Newmarket",
    "Niagara Falls",
    "Niagara-on-the-Lake",
    "Nipigon",
    "Nipissing",
    "Norfolk County",
    "North Algona Wilberforce",
    "North Bay",
    "North Dumfries",
    "North Dundas",
    "North Frontenac",
    "North Glengarry",
    "North Grenville",
    "North Huron",
    "North Kawartha",
    "North Middlesex",
    "North Perth",
    "North Stormont",
    "North York",
    "Northeastern Manitoulin and The Islands",
    "Northern Bruce Peninsula",
    "Norwich",
    "O'Connor",
    "Oakville",
    "Oil Springs",
    "Oliver Paipoonge",
    "Opasatika",
    "Orangeville",
    "Orillia",
    "Oro-Medonte",
    "Oshawa",
    "Otonabee-South Monaghan",
    "Ottawa",
    "Owen Sound",
    "Papineau-Cameron",
    "Parry Sound",
    "Pelee",
    "Pelham",
    "Pembroke",
    "Penetanguishene",
    "Perry",
    "Perth",
    "Perth East",
    "Perth South",
    "Petawawa",
    "Peterborough",
    "Petrolia",
    "Pickering",
    "Pickle Lake",
    "Plummer Additional",
    "Plympton-Wyoming",
    "Point Edward",
    "Port Colborne",
    "Port Hope",
    "Powassan",
    "Prescott",
    "Prince",
    "Prince Edward County",
    "Puslinch",
    "Quinte West",
    "Rainy River",
    "Ramara",
    "Red Lake",
    "Red Rock",
    "Renfrew",
    "Richmond Hill",
    "Rideau Lakes",
    "Russell",
    "Ryerson",
    "Sables-Spanish Rivers",
    "Sarnia",
    "Saugeen Shores",
    "Sault Ste. Marie",
    "Schreiber",
    "Scugog",
    "Seguin",
    "Selwyn",
    "Severn",
    "Shelburne",
    "Shuniah",
    "Sioux Lookout",
    "Sioux Narrows-Nestor Falls",
    "Smiths Falls",
    "Smooth Rock Falls",
    "South Algonquin",
    "South Bruce",
    "South Bruce Peninsula",
    "South Dundas",
    "South Frontenac",
    "South Glengarry",
    "South Huron",
    "South River",
    "South Stormont",
    "South-West Oxford",
    "Southgate",
    "Southwest Middlesex",
    "Southwold",
    "Spanish",
    "Springwater",
    "St. Catharines",
    "St. Clair",
    "St. Joseph",
    "St. Marys",
    "St. Thomas",
    "St.-Charles",
    "Stirling-Rawdon",
    "Stone Mills",
    "Stratford",
    "Strathroy-Caradoc",
    "Strong",
    "Sudbury",
    "Sundridge",
    "Tarbutt",
    "Tarbutt and Tarbutt Additional",
    "Tay",
    "Tay Valley",
    "Tecumseh",
    "Tehkummah",
    "Temagami",
    "Temiskaming Shores",
    "Terrace Bay",
    "Thames Centre",
    "The Archipelago",
    "The Blue Mountains",
    "The Nation",
    "The Nation Municipality",
    "The North Shore",
    "Thessalon",
    "Thornloe",
    "Thorold",
    "Thunder Bay",
    "Tillsonburg",
    "Timmins",
    "Tiny",
    "Toronto",
    "Trent Hills",
    "Trent Lakes",
    "Tudor and Cashel",
    "Tweed",
    "Tyendinaga",
    "Uxbridge",
    "Val Rita-Harty",
    "Vaughan",
    "Wainfleet",
    "Warwick",
    "Wasaga Beach",
    "Waterloo",
    "Wawa",
    "Welland",
    "Wellesley",
    "Wellington North",
    "West Elgin",
    "West Grey",
    "West Lincoln",
    "West Nipissing",
    "West Perth",
    "Westport",
    "Whitby",
    "Whitchurch-Stouffville",
    "White River",
    "Whitestone",
    "Whitewater Region",
    "Wilmot",
    "Windsor",
    "Wollaston",
    "Woodstock",
    "Woolwich",
    "Zorra",
  ],
  PE: [
    "Abram-Village",
    "Alberton",
    "Alexandra",
    "Annandale - Little Pond - Howe Bay",
    "Bedeque and Area",
    "Belfast",
    "Borden",
    "Borden-Carleton",
    "Brackley",
    "Breadalbane",
    "Cardigan",
    "Central Kings",
    "Central Prince",
    "Charlottetown",
    "Clyde River",
    "Cornwall",
    "Crapaud",
    "Crapaud, Part 1",
    "Crapaud, Part 2",
    "Crossroads",
    "Darlington",
    "East River, Part 1",
    "East River, Part 2",
    "Eastern Kings",
    "Greenmount-Montrose",
    "Hampshire",
    "Hazelbrook",
    "Hunter River",
    "Johnstons River",
    "Kensington",
    "Kensington, Part 1",
    "Kensington, Part 2",
    "Kingston",
    "Kinkora",
    "Linkletter",
    "Lot 11 and Area",
    "Malpeque Bay",
    "Miltonvale Park",
    "Miminegash",
    "Miscouche",
    "Montague",
    "Morell",
    "Mount Stewart",
    "Murray Harbour",
    "Murray River",
    "Murray River, Part 1",
    "Murray River, Part 2",
    "New Glasgow",
    "New London",
    "North River",
    "North Rustico",
    "North Shore",
    "North Wiltshire",
    "Northport",
    "O'Leary",
    "Sherbrooke",
    "Souris",
    "Souris West",
    "St. Felix",
    "St. Louis",
    "St. Nicholas",
    "St. Peters",
    "St. Peters Bay",
    "Stanley Bridge, Hope River, Bayview, Cavendish and North Rustico",
    "Stratford",
    "Summerside",
    "Three Rivers",
    "Tignish",
    "Tignish Shore",
    "Tyne Valley",
    "Union Road",
    "Vernon River",
    "Victoria",
    "Warren Grove",
    "Wellington",
    "West Point",
    "West River",
    "Winsloe North",
    "York",
  ],
  QC: [
    "Abercorn",
    "Acton Vale",
    "Adstock",
    "Aguanish",
    "Akulivik",
    "Albanel",
    "Albertville",
    "Alleyn-et-Cawood",
    "Alma",
    "Amherst",
    "Amos",
    "Amqui",
    "Ange-Gardien",
    "Armagh",
    "Arundel",
    "Ascot Corner",
    "Aston-Jonction",
    "Auclair",
    "Audet",
    "Aumond",
    "Aupaluk",
    "Austin",
    "Authier",
    "Authier-Nord",
    "Ayer's Cliff",
    "Baie-Comeau",
    "Baie-D'Urfé",
    "Baie-des-Sables",
    "Baie-du-Febvre",
    "Baie-Johan-Beetz",
    "Baie-Saint-Paul",
    "Baie-Sainte-Catherine",
    "Baie-Trinité",
    "Barkmere",
    "Barnston-Ouest",
    "Barraute",
    "Batiscan",
    "Beaconsfield",
    "Beauceville",
    "Beauharnois",
    "Beaulac-Garthby",
    "Beaumont",
    "Beaupré",
    "Bedford",
    "Belcourt",
    "Belleterre",
    "Beloeil",
    "Berry",
    "Berthier-sur-Mer",
    "Berthierville",
    "Biencourt",
    "Blainville",
    "Blanc-Sablon",
    "Blue Sea",
    "Boileau",
    "Bois-des-Filion",
    "Bois-Franc",
    "Boisbriand",
    "Boischatel",
    "Bolton-Est",
    "Bolton-Ouest",
    "Bonaventure",
    "Bonne-Espérance",
    "Bonsecours",
    "Boucherville",
    "Bouchette",
    "Bowman",
    "Brigham",
    "Bristol",
    "Brome",
    "Bromont",
    "Brossard",
    "Brownsburg-Chatham",
    "Bryson",
    "Brébeuf",
    "Bury",
    "Béarn",
    "Bécancour",
    "Bégin",
    "Béthanie",
    "Cacouna",
    "Calixa-Lavallée",
    "Campbell's Bay",
    "Candiac",
    "Cantley",
    "Cap-Chat",
    "Cap-Saint-Ignace",
    "Cap-Santé",
    "Caplan",
    "Carignan",
    "Carleton-sur-Mer",
    "Cascapédia--Saint-Jules",
    "Causapscal",
    "Cayamant",
    "Chambly",
    "Chambord",
    "Champlain",
    "Champneuf",
    "Chandler",
    "Chapais",
    "Charette",
    "Charlemagne",
    "Chartierville",
    "Chazel",
    "Chelsea",
    "Chertsey",
    "Chesterville",
    "Chibougamau",
    "Chichester",
    "Chute-aux-Outardes",
    "Chute-Saint-Philippe",
    "Château-Richer",
    "Châteauguay",
    "Chénéville",
    "Clarendon",
    "Clermont",
    "Clerval",
    "Cleveland",
    "Cloridorme",
    "Coaticook",
    "Colombier",
    "Compton",
    "Contrecoeur",
    "Cookshire-Eaton",
    "Coteau-du-Lac",
    "Courcelles",
    "Cowansville",
    "Crabtree",
    "Côte-Nord-du-Golfe-du-Saint-Laurent",
    "Côte-Saint-Luc",
    "Danville",
    "Daveluyville",
    "Delson",
    "Denholm",
    "Desbiens",
    "Deschaillons-sur-Saint-Laurent",
    "Deschambault-Grondines",
    "Deux-Montagnes",
    "Disraeli",
    "Dixville",
    "Dolbeau-Mistassini",
    "Dollard-Des Ormeaux",
    "Donnacona",
    "Dorval",
    "Dosquet",
    "Drummondville",
    "Dudswell",
    "Duhamel",
    "Duhamel-Ouest",
    "Dundee",
    "Dunham",
    "Duparquet",
    "Dupuy",
    "Durham-Sud",
    "Dégelis",
    "Déléage",
    "East Angus",
    "East Broughton",
    "East Farnham",
    "East Hereford",
    "Eastman",
    "Egan-Sud",
    "Elgin",
    "Entrelacs",
    "Escuminac",
    "Esprit-Saint",
    "Estérel",
    "Farnham",
    "Fassett",
    "Ferland-et-Boilleau",
    "Ferme-Neuve",
    "Fermont",
    "Forestville",
    "Fort-Coulonge",
    "Fortierville",
    "Fossambault-sur-le-Lac",
    "Frampton",
    "Franklin",
    "Franquelin",
    "Frelighsburg",
    "Frontenac",
    "Fugèreville",
    "Gallichan",
    "Gaspé",
    "Gatineau",
    "Girardville",
    "Godbout",
    "Godmanchester",
    "Gore",
    "Gracefield",
    "Granby",
    "Grand-Métis",
    "Grand-Remous",
    "Grand-Saint-Esprit",
    "Grande-Rivière",
    "Grande-Vallée",
    "Grandes-Piles",
    "Grenville",
    "Grenville-sur-la-Rouge",
    "Gros-Mécatina",
    "Grosse-Île",
    "Grosses-Roches",
    "Guérin",
    "Ham-Nord",
    "Ham-Sud",
    "Hampden",
    "Hampstead",
    "Harrington",
    "Hatley",
    "Havelock",
    "Havre-Saint-Pierre",
    "Hemmingford",
    "Henryville",
    "Hinchinbrooke",
    "Honfleur",
    "Hope",
    "Hope Town",
    "Howick",
    "Huberdeau",
    "Hudson",
    "Huntingdon",
    "Hébertville",
    "Hébertville-Station",
    "Hérouxville",
    "Inukjuak",
    "Inverness",
    "Irlande",
    "Ivry-sur-le-Lac",
    "Ivujivik",
    "Joliette",
    "Kamouraska",
    "Kangiqsualujjuaq",
    "Kangiqsujuaq",
    "Kangirsuk",
    "Kazabazua",
    "Kiamika",
    "Kingsbury",
    "Kingsey Falls",
    "Kinnear's Mills",
    "Kipawa",
    "Kirkland",
    "Kuujjuaq",
    "Kuujjuarapik",
    "L'Ancienne-Lorette",
    "L'Ange-Gardien",
    "L'Anse-Saint-Jean",
    "L'Ascension",
    "L'Ascension-de-Notre-Seigneur",
    "L'Ascension-de-Patapédia",
    "L'Assomption",
    "L'Avenir",
    "L'Isle-aux-Allumettes",
    "L'Isle-aux-Coudres",
    "L'Isle-Verte",
    "L'Islet",
    "L'Épiphanie",
    "L'Île-Cadieux",
    "L'Île-d'Anticosti",
    "L'Île-Dorval",
    "L'Île-du-Grand-Calumet",
    "L'Île-Perrot",
    "La Bostonnais",
    "La Conception",
    "La Corne",
    "La Doré",
    "La Durantaye",
    "La Guadeloupe",
    "La Macaza",
    "La Malbaie",
    "La Martre",
    "La Minerve",
    "La Morandière",
    "La Motte",
    "La Patrie",
    "La Pocatière",
    "La Prairie",
    "La Présentation",
    "La Pêche",
    "La Reine",
    "La Rédemption",
    "La Sarre",
    "La Trinité-des-Monts",
    "La Tuque",
    "La Visitation-de-l'Île-Dupas",
    "La Visitation-de-Yamaska",
    "Labelle",
    "Labrecque",
    "Lac-au-Saumon",
    "Lac-aux-Sables",
    "Lac-Beauport",
    "Lac-Bouchette",
    "Lac-Brome",
    "Lac-Delage",
    "Lac-des-Aigles",
    "Lac-des-Plages",
    "Lac-des-Seize-Îles",
    "Lac-des-Écorces",
    "Lac-Drolet",
    "Lac-du-Cerf",
    "Lac-Etchemin",
    "Lac-Frontière",
    "Lac-Mégantic",
    "Lac-Poulin",
    "Lac-Saguay",
    "Lac-Saint-Joseph",
    "Lac-Saint-Paul",
    "Lac-Sainte-Marie",
    "Lac-Sergent",
    "Lac-Simon",
    "Lac-Supérieur",
    "Lac-Tremblant-Nord",
    "Lac-Édouard",
    "Lachute",
    "Lacolle",
    "Laforce",
    "Lamarche",
    "Lambton",
    "Landrienne",
    "Lanoraie",
    "Lantier",
    "Larouche",
    "Latulipe-et-Gaboury",
    "Launay",
    "Laurier-Station",
    "Laurierville",
    "Laval",
    "Lavaltrie",
    "Laverlochère-Angliers",
    "Lawrenceville",
    "Lebel-sur-Quévillon",
    "Leclercville",
    "Lefebvre",
    "Lejeune",
    "Lemieux",
    "Les Bergeronnes",
    "Les Coteaux",
    "Les Cèdres",
    "Les Escoumins",
    "Les Hauteurs",
    "Les Méchins",
    "Les Éboulements",
    "Les Îles-de-la-Madeleine",
    "Lingwick",
    "Litchfield",
    "Lochaber",
    "Lochaber-Partie-Ouest",
    "Longue-Pointe-de-Mingan",
    "Longue-Rive",
    "Longueuil",
    "Lorraine",
    "Lorrainville",
    "Lotbinière",
    "Louiseville",
    "Low",
    "Lyster",
    "Léry",
    "Lévis",
    "Macamic",
    "Maddington Falls",
    "Magog",
    "Malartic",
    "Mandeville",
    "Maniwaki",
    "Manseau",
    "Mansfield-et-Pontefract",
    "Maria",
    "Maricourt",
    "Marieville",
    "Marsoui",
    "Marston",
    "Martinville",
    "Mascouche",
    "Maskinongé",
    "Massueville",
    "Matagami",
    "Matane",
    "Matapédia",
    "Mayo",
    "McMasterville",
    "Melbourne",
    "Mercier",
    "Messines",
    "Milan",
    "Mille-Isles",
    "Mirabel",
    "Moffet",
    "Mont-Carmel",
    "Mont-Joli",
    "Mont-Laurier",
    "Mont-Royal",
    "Mont-Saint-Grégoire",
    "Mont-Saint-Hilaire",
    "Mont-Saint-Michel",
    "Mont-Saint-Pierre",
    "Mont-Tremblant",
    "Montcalm",
    "Montcerf-Lytton",
    "Montebello",
    "Montmagny",
    "Montpellier",
    "Montreal",
    "Montréal-Est",
    "Montréal-Ouest",
    "Morin-Heights",
    "Mulgrave-et-Derry",
    "Murdochville",
    "Métabetchouan--Lac-à-la-Croix",
    "Métis-sur-Mer",
    "Namur",
    "Nantes",
    "Napierville",
    "Natashquan",
    "Neuville",
    "New Carlisle",
    "New Richmond",
    "Newport",
    "Nicolet",
    "Nominingue",
    "Normandin",
    "Normétal",
    "North Hatley",
    "Notre-Dame-Auxiliatrice-de-Buckland",
    "Notre-Dame-de-Bonsecours",
    "Notre-Dame-de-Ham",
    "Notre-Dame-de-l'Île-Perrot",
    "Notre-Dame-de-la-Merci",
    "Notre-Dame-de-la-Paix",
    "Notre-Dame-de-la-Salette",
    "Notre-Dame-de-Lorette",
    "Notre-Dame-de-Lourdes",
    "Notre-Dame-de-Montauban",
    "Notre-Dame-de-Pontmain",
    "Notre-Dame-de-Stanbridge",
    "Notre-Dame-des-Anges",
    "Notre-Dame-des-Bois",
    "Notre-Dame-des-Monts",
    "Notre-Dame-des-Neiges",
    "Notre-Dame-des-Pins",
    "Notre-Dame-des-Prairies",
    "Notre-Dame-des-Sept-Douleurs",
    "Notre-Dame-du-Bon-Conseil",
    "Notre-Dame-du-Laus",
    "Notre-Dame-du-Mont-Carmel",
    "Notre-Dame-du-Nord",
    "Notre-Dame-du-Portage",
    "Notre-Dame-du-Rosaire",
    "Notre-Dame-du-Sacré-Coeur-d'Issoudun",
    "Nouvelle",
    "Noyan",
    "Nédélec",
    "Ogden",
    "Oka",
    "Orford",
    "Ormstown",
    "Otter Lake",
    "Otterburn Park",
    "Packington",
    "Padoue",
    "Palmarolle",
    "Papineauville",
    "Parisville",
    "Paspébiac",
    "Percé",
    "Petit-Saguenay",
    "Petite-Rivière-Saint-François",
    "Petite-Vallée",
    "Piedmont",
    "Pierreville",
    "Pike River",
    "Pincourt",
    "Piopolis",
    "Plaisance",
    "Plessisville",
    "Pohénégamook",
    "Pointe-aux-Outardes",
    "Pointe-Calumet",
    "Pointe-Claire",
    "Pointe-des-Cascades",
    "Pointe-Fortune",
    "Pointe-Lebel",
    "Pointe-à-la-Croix",
    "Pont-Rouge",
    "Pontiac",
    "Port-Cartier",
    "Port-Daniel--Gascons",
    "Portage-du-Fort",
    "Portneuf",
    "Portneuf-sur-Mer",
    "Potton",
    "Poularies",
    "Preissac",
    "Price",
    "Princeville",
    "Prévost",
    "Puvirnituq",
    "Péribonka",
    "Quaqtaq",
    "Québec",
    "Racine",
    "Ragueneau",
    "Rapide-Danseur",
    "Rapides-des-Joachims",
    "Rawdon",
    "Repentigny",
    "Richelieu",
    "Richmond",
    "Rigaud",
    "Rimouski",
    "Ripon",
    "Ristigouche-Partie-Sud-Est",
    "Rivière-au-Tonnerre",
    "Rivière-Beaudette",
    "Rivière-Bleue",
    "Rivière-du-Loup",
    "Rivière-Héva",
    "Rivière-Ouelle",
    "Rivière-Rouge",
    "Rivière-Saint-Jean",
    "Rivière-à-Claude",
    "Rivière-à-Pierre",
    "Rivière-Éternité",
    "Roberval",
    "Rochebaucourt",
    "Roquemaure",
    "Rosemère",
    "Rougemont",
    "Rouyn-Noranda",
    "Roxton",
    "Roxton Falls",
    "Roxton Pond",
    "Rémigny",
    "Sacré-Coeur",
    "Sacré-Coeur-de-Jésus",
    "Saguenay",
    "Saint-Adalbert",
    "Saint-Adelme",
    "Saint-Adelphe",
    "Saint-Adolphe-d'Howard",
    "Saint-Adrien",
    "Saint-Adrien-d'Irlande",
    "Saint-Agapit",
    "Saint-Aimé",
    "Saint-Aimé-des-Lacs",
    "Saint-Aimé-du-Lac-des-Îles",
    "Saint-Alban",
    "Saint-Albert",
    "Saint-Alexandre",
    "Saint-Alexandre-de-Kamouraska",
    "Saint-Alexandre-des-Lacs",
    "Saint-Alexis",
    "Saint-Alexis-de-Matapédia",
    "Saint-Alexis-des-Monts",
    "Saint-Alfred",
    "Saint-Alphonse",
    "Saint-Alphonse-de-Granby",
    "Saint-Alphonse-Rodriguez",
    "Saint-Amable",
    "Saint-Ambroise",
    "Saint-Ambroise-de-Kildare",
    "Saint-Anaclet-de-Lessard",
    "Saint-André-Avellin",
    "Saint-André-d'Argenteuil",
    "Saint-André-de-Kamouraska",
    "Saint-André-de-Restigouche",
    "Saint-André-du-Lac-Saint-Jean",
    "Saint-Anicet",
    "Saint-Anselme",
    "Saint-Antoine-de-l'Isle-aux-Grues",
    "Saint-Antoine-de-Tilly",
    "Saint-Antoine-sur-Richelieu",
    "Saint-Antonin",
    "Saint-Apollinaire",
    "Saint-Armand",
    "Saint-Arsène",
    "Saint-Athanase",
    "Saint-Aubert",
    "Saint-Augustin",
    "Saint-Augustin-de-Desmaures",
    "Saint-Augustin-de-Woburn",
    "Saint-Barnabé",
    "Saint-Barnabé-Sud",
    "Saint-Barthélemy",
    "Saint-Basile",
    "Saint-Basile-le-Grand",
    "Saint-Benjamin",
    "Saint-Benoît-du-Lac",
    "Saint-Benoît-Labre",
    "Saint-Bernard",
    "Saint-Bernard-de-Lacolle",
    "Saint-Bernard-de-Michaudville",
    "Saint-Blaise-sur-Richelieu",
    "Saint-Bonaventure",
    "Saint-Boniface",
    "Saint-Bruno",
    "Saint-Bruno-de-Guigues",
    "Saint-Bruno-de-Kamouraska",
    "Saint-Bruno-de-Montarville",
    "Saint-Calixte",
    "Saint-Camille",
    "Saint-Camille-de-Lellis",
    "Saint-Casimir",
    "Saint-Charles-Borromée",
    "Saint-Charles-de-Bellechasse",
    "Saint-Charles-de-Bourget",
    "Saint-Charles-Garnier",
    "Saint-Charles-sur-Richelieu",
    "Saint-Christophe-d'Arthabaska",
    "Saint-Chrysostome",
    "Saint-Claude",
    "Saint-Clet",
    "Saint-Clément",
    "Saint-Cléophas",
    "Saint-Cléophas-de-Brandon",
    "Saint-Colomban",
    "Saint-Constant",
    "Saint-Cuthbert",
    "Saint-Cyprien",
    "Saint-Cyprien-de-Napierville",
    "Saint-Cyrille-de-Lessard",
    "Saint-Cyrille-de-Wendover",
    "Saint-Célestin",
    "Saint-Césaire",
    "Saint-Côme",
    "Saint-Côme--Linière",
    "Saint-Damase",
    "Saint-Damase-de-L'Islet",
    "Saint-Damien",
    "Saint-Damien-de-Buckland",
    "Saint-David",
    "Saint-David-de-Falardeau",
    "Saint-Denis-De La Bouteillerie",
    "Saint-Denis-de-Brompton",
    "Saint-Denis-sur-Richelieu",
    "Saint-Didace",
    "Saint-Dominique",
    "Saint-Dominique-du-Rosaire",
    "Saint-Donat",
    "Saint-Edmond-de-Grantham",
    "Saint-Edmond-les-Plaines",
    "Saint-Elphège",
    "Saint-Elzéar",
    "Saint-Elzéar-de-Témiscouata",
    "Saint-Esprit",
    "Saint-Eugène",
    "Saint-Eugène-d'Argentenay",
    "Saint-Eugène-de-Guigues",
    "Saint-Eugène-de-Ladrière",
    "Saint-Eustache",
    "Saint-Eusèbe",
    "Saint-Fabien",
    "Saint-Fabien-de-Panet",
    "Saint-Faustin--Lac-Carré",
    "Saint-Ferdinand",
    "Saint-Ferréol-les-Neiges",
    "Saint-Flavien",
    "Saint-Fortunat",
    "Saint-François-d'Assise",
    "Saint-François-de-l'Île-d'Orléans",
    "Saint-François-de-la-Rivière-du-Sud",
    "Saint-François-de-Sales",
    "Saint-François-du-Lac",
    "Saint-François-Xavier-de-Brompton",
    "Saint-François-Xavier-de-Viger",
    "Saint-Frédéric",
    "Saint-Fulgence",
    "Saint-Félicien",
    "Saint-Félix-d'Otis",
    "Saint-Félix-de-Dalquier",
    "Saint-Félix-de-Kingsey",
    "Saint-Félix-de-Valois",
    "Saint-Gabriel",
    "Saint-Gabriel-de-Brandon",
    "Saint-Gabriel-de-Rimouski",
    "Saint-Gabriel-de-Valcartier",
    "Saint-Gabriel-Lalemant",
    "Saint-Georges",
    "Saint-Georges-de-Clarenceville",
    "Saint-Georges-de-Windsor",
    "Saint-Germain",
    "Saint-Germain-de-Grantham",
    "Saint-Gervais",
    "Saint-Gilbert",
    "Saint-Gilles",
    "Saint-Godefroi",
    "Saint-Guillaume",
    "Saint-Guy",
    "Saint-Gédéon",
    "Saint-Gédéon-de-Beauce",
    "Saint-Gérard-Majella",
    "Saint-Henri",
    "Saint-Henri-de-Taillon",
    "Saint-Herménégilde",
    "Saint-Hilaire-de-Dorset",
    "Saint-Hilarion",
    "Saint-Hippolyte",
    "Saint-Honoré",
    "Saint-Honoré-de-Shenley",
    "Saint-Honoré-de-Témiscouata",
    "Saint-Hubert-de-Rivière-du-Loup",
    "Saint-Hugues",
    "Saint-Hyacinthe",
    "Saint-Ignace-de-Loyola",
    "Saint-Ignace-de-Stanbridge",
    "Saint-Irénée",
    "Saint-Isidore",
    "Saint-Isidore-de-Clifton",
    "Saint-Jacques",
    "Saint-Jacques-de-Leeds",
    "Saint-Jacques-le-Majeur-de-Wolfestown",
    "Saint-Jacques-le-Mineur",
    "Saint-Janvier-de-Joly",
    "Saint-Jean-Baptiste",
    "Saint-Jean-de-Brébeuf",
    "Saint-Jean-de-Cherbourg",
    "Saint-Jean-de-Dieu",
    "Saint-Jean-de-l'Île-d'Orléans",
    "Saint-Jean-de-la-Lande",
    "Saint-Jean-de-Matha",
    "Saint-Jean-Port-Joli",
    "Saint-Jean-sur-Richelieu",
    "Saint-Joachim",
    "Saint-Joachim-de-Shefford",
    "Saint-Joseph-de-Beauce",
    "Saint-Joseph-de-Coleraine",
    "Saint-Joseph-de-Kamouraska",
    "Saint-Joseph-de-Lepage",
    "Saint-Joseph-de-Sorel",
    "Saint-Joseph-des-Érables",
    "Saint-Joseph-du-Lac",
    "Saint-Jude",
    "Saint-Jules",
    "Saint-Julien",
    "Saint-Just-de-Bretenières",
    "Saint-Juste-du-Lac",
    "Saint-Justin",
    "Saint-Jérôme",
    "Saint-Lambert",
    "Saint-Lambert-de-Lauzon",
    "Saint-Laurent-de-l'Île-d'Orléans",
    "Saint-Lazare",
    "Saint-Lazare-de-Bellechasse",
    "Saint-Liboire",
    "Saint-Liguori",
    "Saint-Lin--Laurentides",
    "Saint-Louis",
    "Saint-Louis-de-Blandford",
    "Saint-Louis-de-Gonzague",
    "Saint-Louis-de-Gonzague-du-Cap-Tourmente",
    "Saint-Louis-du-Ha! Ha!",
    "Saint-Luc-de-Bellechasse",
    "Saint-Luc-de-Vincennes",
    "Saint-Lucien",
    "Saint-Ludger",
    "Saint-Ludger-de-Milot",
    "Saint-Léandre",
    "Saint-Léon-de-Standon",
    "Saint-Léon-le-Grand",
    "Saint-Léonard-d'Aston",
    "Saint-Léonard-de-Portneuf",
    "Saint-Magloire",
    "Saint-Majorique-de-Grantham",
    "Saint-Malachie",
    "Saint-Malo",
    "Saint-Marc-de-Figuery",
    "Saint-Marc-des-Carrières",
    "Saint-Marc-du-Lac-Long",
    "Saint-Marc-sur-Richelieu",
    "Saint-Marcel",
    "Saint-Marcel-de-Richelieu",
    "Saint-Marcellin",
    "Saint-Martin",
    "Saint-Mathias-sur-Richelieu",
    "Saint-Mathieu",
    "Saint-Mathieu-d'Harricana",
    "Saint-Mathieu-de-Beloeil",
    "Saint-Mathieu-de-Rioux",
    "Saint-Mathieu-du-Parc",
    "Saint-Maurice",
    "Saint-Maxime-du-Mont-Louis",
    "Saint-Michel",
    "Saint-Michel-de-Bellechasse",
    "Saint-Michel-des-Saints",
    "Saint-Michel-du-Squatec",
    "Saint-Modeste",
    "Saint-Moïse",
    "Saint-Médard",
    "Saint-Narcisse",
    "Saint-Narcisse-de-Beaurivage",
    "Saint-Narcisse-de-Rimouski",
    "Saint-Nazaire",
    "Saint-Nazaire-d'Acton",
    "Saint-Nazaire-de-Dorchester",
    "Saint-Norbert",
    "Saint-Norbert-d'Arthabaska",
    "Saint-Noël",
    "Saint-Nérée-de-Bellechasse",
    "Saint-Octave-de-Métis",
    "Saint-Odilon-de-Cranbourne",
    "Saint-Omer",
    "Saint-Onésime-d'Ixworth",
    "Saint-Ours",
    "Saint-Pacôme",
    "Saint-Pamphile",
    "Saint-Pascal",
    "Saint-Patrice-de-Beaurivage",
    "Saint-Patrice-de-Sherrington",
    "Saint-Paul",
    "Saint-Paul-d'Abbotsford",
    "Saint-Paul-de-l'Île-aux-Noix",
    "Saint-Paul-de-la-Croix",
    "Saint-Paul-de-Montminy",
    "Saint-Paulin",
    "Saint-Philibert",
    "Saint-Philippe",
    "Saint-Philippe-de-Néri",
    "Saint-Philémon",
    "Saint-Pie",
    "Saint-Pie-de-Guire",
    "Saint-Pierre",
    "Saint-Pierre-Baptiste",
    "Saint-Pierre-de-Broughton",
    "Saint-Pierre-de-l'Île-d'Orléans",
    "Saint-Pierre-de-la-Rivière-du-Sud",
    "Saint-Pierre-de-Lamy",
    "Saint-Pierre-les-Becquets",
    "Saint-Placide",
    "Saint-Polycarpe",
    "Saint-Prime",
    "Saint-Prosper",
    "Saint-Prosper-de-Champlain",
    "Saint-Raphaël",
    "Saint-Raymond",
    "Saint-René",
    "Saint-René-de-Matane",
    "Saint-Robert",
    "Saint-Robert-Bellarmin",
    "Saint-Roch-de-l'Achigan",
    "Saint-Roch-de-Mékinac",
    "Saint-Roch-de-Richelieu",
    "Saint-Roch-des-Aulnaies",
    "Saint-Roch-Ouest",
    "Saint-Romain",
    "Saint-Rosaire",
    "Saint-Rémi",
    "Saint-Rémi-de-Tingwick",
    "Saint-Samuel",
    "Saint-Sauveur",
    "Saint-Simon",
    "Saint-Simon-de-Rimouski",
    "Saint-Simon-les-Mines",
    "Saint-Siméon",
    "Saint-Sixte",
    "Saint-Stanislas",
    "Saint-Stanislas-de-Kostka",
    "Saint-Sulpice",
    "Saint-Sylvestre",
    "Saint-Sylvère",
    "Saint-Sébastien",
    "Saint-Séverin",
    "Saint-Sévère",
    "Saint-Tharcisius",
    "Saint-Thomas",
    "Saint-Thomas-Didyme",
    "Saint-Thuribe",
    "Saint-Théodore-d'Acton",
    "Saint-Théophile",
    "Saint-Tite",
    "Saint-Tite-des-Caps",
    "Saint-Télesphore",
    "Saint-Ubalde",
    "Saint-Ulric",
    "Saint-Urbain",
    "Saint-Urbain-Premier",
    "Saint-Valentin",
    "Saint-Vallier",
    "Saint-Valère",
    "Saint-Valérien",
    "Saint-Valérien-de-Milton",
    "Saint-Venant-de-Paquette",
    "Saint-Vianney",
    "Saint-Victor",
    "Saint-Wenceslas",
    "Saint-Zacharie",
    "Saint-Zotique",
    "Saint-Zénon",
    "Saint-Zénon-du-Lac-Humqui",
    "Saint-Zéphirin-de-Courval",
    "Saint-Édouard",
    "Saint-Édouard-de-Fabre",
    "Saint-Édouard-de-Lotbinière",
    "Saint-Édouard-de-Maskinongé",
    "Saint-Élie-de-Caxton",
    "Saint-Éloi",
    "Saint-Émile-de-Suffolk",
    "Saint-Éphrem-de-Beauce",
    "Saint-Épiphane",
    "Saint-Étienne-de-Beauharnois",
    "Saint-Étienne-de-Bolton",
    "Saint-Étienne-des-Grès",
    "Saint-Évariste-de-Forsyth",
    "Sainte-Adèle",
    "Sainte-Agathe-de-Lotbinière",
    "Sainte-Agathe-des-Monts",
    "Sainte-Angèle-de-Monnoir",
    "Sainte-Angèle-de-Mérici",
    "Sainte-Angèle-de-Prémont",
    "Sainte-Anne-de-Beaupré",
    "Sainte-Anne-de-Bellevue",
    "Sainte-Anne-de-la-Pocatière",
    "Sainte-Anne-de-la-Pérade",
    "Sainte-Anne-de-la-Rochelle",
    "Sainte-Anne-de-Sabrevois",
    "Sainte-Anne-de-Sorel",
    "Sainte-Anne-des-Lacs",
    "Sainte-Anne-des-Monts",
    "Sainte-Anne-des-Plaines",
    "Sainte-Anne-du-Lac",
    "Sainte-Apolline-de-Patton",
    "Sainte-Aurélie",
    "Sainte-Barbe",
    "Sainte-Brigide-d'Iberville",
    "Sainte-Brigitte-de-Laval",
    "Sainte-Brigitte-des-Saults",
    "Sainte-Béatrix",
    "Sainte-Catherine",
    "Sainte-Catherine-de-Hatley",
    "Sainte-Catherine-de-la-Jacques-Cartier",
    "Sainte-Christine",
    "Sainte-Christine-d'Auvergne",
    "Sainte-Claire",
    "Sainte-Clotilde",
    "Sainte-Clotilde-de-Beauce",
    "Sainte-Clotilde-de-Horton",
    "Sainte-Croix",
    "Sainte-Cécile-de-Lévrard",
    "Sainte-Cécile-de-Milton",
    "Sainte-Cécile-de-Whitton",
    "Sainte-Edwidge-de-Clifton",
    "Sainte-Eulalie",
    "Sainte-Euphémie-sur-Rivière-du-Sud",
    "Sainte-Famille-de-l'Île-d'Orléans",
    "Sainte-Flavie",
    "Sainte-Florence",
    "Sainte-Françoise",
    "Sainte-Félicité",
    "Sainte-Geneviève-de-Batiscan",
    "Sainte-Geneviève-de-Berthier",
    "Sainte-Germaine-Boulé",
    "Sainte-Gertrude-Manneville",
    "Sainte-Hedwidge",
    "Sainte-Hélène-de-Bagot",
    "Sainte-Hélène-de-Chester",
    "Sainte-Hélène-de-Kamouraska",
    "Sainte-Hélène-de-Mancebourg",
    "Sainte-Hénédine",
    "Sainte-Irène",
    "Sainte-Jeanne-d'Arc",
    "Sainte-Julie",
    "Sainte-Julienne",
    "Sainte-Justine",
    "Sainte-Justine-de-Newton",
    "Sainte-Louise",
    "Sainte-Luce",
    "Sainte-Lucie-de-Beauregard",
    "Sainte-Lucie-des-Laurentides",
    "Sainte-Madeleine",
    "Sainte-Madeleine-de-la-Rivière-Madeleine",
    "Sainte-Marcelline-de-Kildare",
    "Sainte-Marguerite",
    "Sainte-Marguerite-du-Lac-Masson",
    "Sainte-Marguerite-Marie",
    "Sainte-Marie",
    "Sainte-Marie-de-Blandford",
    "Sainte-Marie-Madeleine",
    "Sainte-Marie-Salomé",
    "Sainte-Marthe",
    "Sainte-Marthe-sur-le-Lac",
    "Sainte-Martine",
    "Sainte-Monique",
    "Sainte-Mélanie",
    "Sainte-Paule",
    "Sainte-Perpétue",
    "Sainte-Praxède",
    "Sainte-Pétronille",
    "Sainte-Rita",
    "Sainte-Rose-de-Watford",
    "Sainte-Rose-du-Nord",
    "Sainte-Sabine",
    "Sainte-Sophie",
    "Sainte-Sophie-d'Halifax",
    "Sainte-Sophie-de-Lévrard",
    "Sainte-Séraphine",
    "Sainte-Thècle",
    "Sainte-Thérèse",
    "Sainte-Thérèse-de-Gaspé",
    "Sainte-Thérèse-de-la-Gatineau",
    "Sainte-Ursule",
    "Sainte-Victoire-de-Sorel",
    "Sainte-Élisabeth",
    "Sainte-Élizabeth-de-Warwick",
    "Sainte-Émélie-de-l'Énergie",
    "Saints-Anges",
    "Saints-Martyrs-Canadiens",
    "Salaberry-de-Valleyfield",
    "Salluit",
    "Sayabec",
    "Schefferville",
    "Scotstown",
    "Scott",
    "Senneterre",
    "Senneville",
    "Sept-Îles",
    "Shannon",
    "Shawinigan",
    "Shawville",
    "Sheenboro",
    "Shefford",
    "Sherbrooke",
    "Shigawake",
    "Sorel-Tracy",
    "Stanbridge East",
    "Stanbridge Station",
    "Stanstead",
    "Stanstead-Est",
    "Stoke",
    "Stoneham-et-Tewkesbury",
    "Stornoway",
    "Stratford",
    "Stukely-Sud",
    "Sutton",
    "Tadoussac",
    "Taschereau",
    "Tasiujaq",
    "Terrasse-Vaudreuil",
    "Terrebonne",
    "Thetford Mines",
    "Thorne",
    "Thurso",
    "Tingwick",
    "Tourville",
    "Tring-Jonction",
    "Trois-Pistoles",
    "Trois-Rives",
    "Trois-Rivières",
    "Très-Saint-Rédempteur",
    "Très-Saint-Sacrement",
    "Trécesson",
    "Témiscaming",
    "Témiscouata-sur-le-Lac",
    "Ulverton",
    "Umiujaq",
    "Upton",
    "Val-Alain",
    "Val-Brillant",
    "Val-d'Or",
    "Val-David",
    "Val-des-Bois",
    "Val-des-Lacs",
    "Val-des-Monts",
    "Val-des-Sources",
    "Val-Joli",
    "Val-Morin",
    "Val-Racine",
    "Val-Saint-Gilles",
    "Valcourt",
    "Vallée-Jonction",
    "Varennes",
    "Vaudreuil-Dorion",
    "Vaudreuil-sur-le-Lac",
    "Venise-en-Québec",
    "Verchères",
    "Victoriaville",
    "Ville-Marie",
    "Villeroy",
    "Waltham",
    "Warden",
    "Warwick",
    "Waterloo",
    "Waterville",
    "Weedon",
    "Wentworth",
    "Wentworth-Nord",
    "Westbury",
    "Westmount",
    "Wickham",
    "Windsor",
    "Wotton",
    "Yamachiche",
    "Yamaska",
  ],
  SK: [
    "Abbey",
    "Aberdeen",
    "Aberdeen No. 373",
    "Abernethy",
    "Abernethy No. 186",
    "Air Ronge",
    "Alameda",
    "Albertville",
    "Alice Beach",
    "Alida",
    "Allan",
    "Alvena",
    "Annaheim",
    "Antelope Park No. 322",
    "Antler No. 61",
    "Aquadeo",
    "Arborfield",
    "Arborfield No. 456",
    "Archerwill",
    "Arcola",
    "Argyle No. 1",
    "Arlington No. 79",
    "Arm River No. 252",
    "Arran",
    "Asquith",
    "Assiniboia",
    "Atwater",
    "Auvergne No. 76",
    "Avonlea",
    "Aylesbury",
    "Aylsham",
    "B-Say-Tah",
    "Baildon No. 131",
    "Balcarres",
    "Balgonie",
    "Bangor",
    "Barrier Valley No. 397",
    "Battle River No. 438",
    "Battleford",
    "Bayne No. 371",
    "Beatty",
    "Beauval",
    "Beaver Flat",
    "Beaver River No. 622",
    "Beechy",
    "Belle Plaine",
    "Bengough",
    "Bengough No. 40",
    "Benson No. 35",
    "Bethune",
    "Bienfait",
    "Big Arm No. 251",
    "Big Quill No. 308",
    "Big River",
    "Big River No. 555",
    "Big Shell",
    "Big Stick No. 141",
    "Biggar",
    "Biggar No. 347",
    "Birch Hills",
    "Birch Hills No. 460",
    "Bird's Point",
    "Bjorkdale",
    "Bjorkdale No. 426",
    "Black Point",
    "Bladworth",
    "Blaine Lake",
    "Blaine Lake No. 434",
    "Blucher No. 343",
    "Bone Creek No. 108",
    "Borden",
    "Bracken",
    "Bradwell",
    "Bratt's Lake No. 129",
    "Bredenbury",
    "Briercrest",
    "Britannia No. 502",
    "Broadview",
    "Brock",
    "Brock No. 64",
    "Broderick",
    "Brokenshell No. 68",
    "Browning No. 34",
    "Brownlee",
    "Bruno",
    "Buchanan",
    "Buchanan No. 304",
    "Buckland No. 491",
    "Buena Vista",
    "Buffalo Narrows",
    "Buffalo No. 409",
    "Bulyea",
    "Burstall",
    "Cabri",
    "Cadillac",
    "Calder",
    "Calder No. 241",
    "Caledonia No. 99",
    "Cambria No. 6",
    "Cana No. 214",
    "Canaan No. 225",
    "Candle Lake",
    "Canora",
    "Canwood",
    "Canwood No. 494",
    "Carievale",
    "Carlyle",
    "Carmichael No. 109",
    "Carnduff",
    "Caron No. 162",
    "Caronport",
    "Carrot River",
    "Central Butte",
    "Ceylon",
    "Chamberlain",
    "Chaplin",
    "Chaplin No. 164",
    "Chester No. 125",
    "Chesterfield No. 261",
    "Chitek Lake",
    "Choiceland",
    "Chorney Beach",
    "Christopher Lake",
    "Churchbridge",
    "Churchbridge No. 211",
    "Clavet",
    "Clayton No. 333",
    "Climax",
    "Clinworth No. 230",
    "Coalfields No. 4",
    "Cochin",
    "Coderre",
    "Codette",
    "Cole Bay",
    "Coleville",
    "Colonsay",
    "Colonsay No. 342",
    "Connaught No. 457",
    "Conquest",
    "Consul",
    "Corman Park No. 344",
    "Coronach",
    "Cote No. 271",
    "Coteau Beach",
    "Coteau No. 255",
    "Coulee No. 136",
    "Craik",
    "Craik No. 222",
    "Craven",
    "Creelman",
    "Creighton",
    "Cudworth",
    "Cumberland House",
    "Cupar",
    "Cupar No. 218",
    "Cut Knife",
    "Cut Knife No. 439",
    "Cymri No. 36",
    "Dalmeny",
    "Davidson",
    "Debden",
    "Deer Forks No. 232",
    "Delisle",
    "Denare Beach",
    "Denholm",
    "Denzil",
    "Dilke",
    "Dinsmore",
    "Disley",
    "Dodsland",
    "Dore Lake",
    "Dorintosh",
    "Douglas No. 436",
    "Drake",
    "Drinkwater",
    "Dubuc",
    "Duck Lake",
    "Duck Lake No. 463",
    "Duff",
    "Dufferin No. 190",
    "Dundurn",
    "Dundurn No. 314",
    "Duval",
    "Dysart",
    "Eagle Creek No. 376",
    "Earl Grey",
    "Eastend",
    "Eatonia",
    "Ebenezer",
    "Echo Bay",
    "Edam",
    "Edenwold",
    "Edenwold No. 158",
    "Elbow",
    "Elcapo No. 154",
    "Eldon No. 471",
    "Elfros",
    "Elfros No. 307",
    "Elmsthorpe No. 100",
    "Elrose",
    "Emerald No. 277",
    "Endeavour",
    "Enfield No. 194",
    "Englefeld",
    "Enniskillen No. 3",
    "Enterprise No. 142",
    "Ernfold",
    "Esterhazy",
    "Estevan",
    "Estevan No. 5",
    "Eston",
    "Etters Beach",
    "Excel No. 71",
    "Excelsior No. 166",
    "Eye Hill No. 382",
    "Eyebrow",
    "Eyebrow No. 193",
    "Fairlight",
    "Fenwood",
    "Fertile Belt No. 183",
    "Fertile Valley No. 285",
    "Fillmore",
    "Fillmore No. 96",
    "Findlater",
    "Fish Creek No. 402",
    "Flaxcombe",
    "Fleming",
    "Flett's Springs No. 429",
    "Flin Flon",
    "Foam Lake",
    "Foam Lake No. 276",
    "Forget",
    "Fort Qu'Appelle",
    "Fort San",
    "Fosston",
    "Fox Valley",
    "Fox Valley No. 171",
    "Francis",
    "Francis No. 127",
    "Frenchman Butte No. 501",
    "Frobisher",
    "Frontier",
    "Frontier No. 19",
    "Gainsborough",
    "Garden River No. 490",
    "Garry No. 245",
    "Gerald",
    "Glaslyn",
    "Glen Bain No. 105",
    "Glen Ewen",
    "Glen Harbour",
    "Glen McPherson No. 46",
    "Glenavon",
    "Glenside",
    "Glenside No. 377",
    "Golden Prairie",
    "Golden West No. 95",
    "Good Lake No. 274",
    "Goodeve",
    "Goodsoil",
    "Goodwater",
    "Govan",
    "Grand Coulee",
    "Grandview Beach",
    "Grandview No. 349",
    "Grant No. 372",
    "Grass Lake No. 381",
    "Grassy Creek No. 78",
    "Gravelbourg",
    "Gravelbourg No. 104",
    "Grayson",
    "Grayson No. 184",
    "Great Bend No. 405",
    "Green Lake",
    "Greig Lake",
    "Grenfell",
    "Griffin No. 66",
    "Gull Lake",
    "Gull Lake No. 139",
    "Hafford",
    "Hague",
    "Halbrite",
    "Hanley",
    "Happy Valley No. 10",
    "Happyland No. 231",
    "Harris",
    "Harris No. 316",
    "Hart Butte No. 11",
    "Hawarden",
    "Hazel Dell No. 335",
    "Hazelwood No. 94",
    "Hazenmore",
    "Hazlet",
    "Heart's Hill No. 352",
    "Hepburn",
    "Herbert",
    "Heward",
    "Hillsborough No. 132",
    "Hillsdale No. 440",
    "Hodgeville",
    "Holdfast",
    "Hoodoo No. 401",
    "Hubbard",
    "Hudson Bay",
    "Hudson Bay No. 394",
    "Humboldt",
    "Humboldt No. 370",
    "Huron No. 223",
    "Hyas",
    "Imperial",
    "Indian Head",
    "Indian Head No. 156",
    "Insinger No. 275",
    "Invergordon No. 430",
    "Invermay",
    "Invermay No. 305",
    "Island View",
    "Ituna",
    "Ituna Bon Accord No. 246",
    "Jans Bay",
    "Jansen",
    "Kamsack",
    "Kannata Valley",
    "Katepwa",
    "Kelliher",
    "Kellross No. 247",
    "Kelvington",
    "Kelvington No. 366",
    "Kenaston",
    "Kendal",
    "Kennedy",
    "Kenosee Lake",
    "Kerrobert",
    "Key West No. 70",
    "Keys No. 303",
    "Killaly",
    "Kincaid",
    "Kindersley",
    "Kindersley No. 290",
    "King George No. 256",
    "Kingsley No. 124",
    "Kinistino",
    "Kinistino No. 459",
    "Kinley",
    "Kipling",
    "Kisbey",
    "Kivimaa-Moonlight Bay",
    "Krydor",
    "Kyle",
    "La Loche",
    "La Ronge",
    "Lac Pelletier No. 107",
    "Lacadena No. 228",
    "Lafleche",
    "Laird",
    "Laird No. 404",
    "Lajord No. 128",
    "Lake Alma No. 8",
    "Lake Johnston No. 102",
    "Lake Lenore",
    "Lake Lenore No. 399",
    "Lake of the Rivers No. 72",
    "Lakeland No. 521",
    "Lakeside No. 338",
    "Lakeview No. 337",
    "Lampman",
    "Lancer",
    "Landis",
    "Lang",
    "Langenburg",
    "Langenburg No. 181",
    "Langham",
    "Lanigan",
    "Lashburn",
    "Last Mountain Valley No. 250",
    "Laurier No. 38",
    "Lawtonia No. 135",
    "Leader",
    "Leask",
    "Leask No. 464",
    "Lebret",
    "Lemberg",
    "Leoville",
    "Leross",
    "Leroy",
    "Leroy No. 339",
    "Leslie Beach",
    "Liberty",
    "Limerick",
    "Lintlaw",
    "Lipton",
    "Lipton No. 217",
    "Livingston No. 331",
    "Lloydminster",
    "Lomond No. 37",
    "Lone Tree No. 18",
    "Longlaketon No. 219",
    "Loon Lake",
    "Loon Lake No. 561",
    "Loreburn",
    "Loreburn No. 254",
    "Lost River No. 313",
    "Love",
    "Lucky Lake",
    "Lumsden",
    "Lumsden Beach",
    "Lumsden No. 189",
    "Luseland",
    "Macklin",
    "MacNutt",
    "Macoun",
    "Macrorie",
    "Maidstone",
    "Major",
    "Makwa",
    "Manitou Beach",
    "Manitou Lake No. 442",
    "Mankota",
    "Mankota No. 45",
    "Manor",
    "Maple Bush No. 224",
    "Maple Creek",
    "Maple Creek No. 111",
    "Marcelin",
    "Marengo",
    "Margo",
    "Mariposa No. 350",
    "Markinch",
    "Marquis",
    "Marquis No. 191",
    "Marriott No. 317",
    "Marsden",
    "Marshall",
    "Martensville",
    "Martin No. 122",
    "Maryfield",
    "Maryfield No. 91",
    "Mayfield No. 406",
    "Maymont",
    "McCraney No. 282",
    "McKillop No. 220",
    "McLean",
    "McLeod No. 185",
    "McTaggart",
    "Meacham",
    "Meadow Lake",
    "Meadow Lake No. 588",
    "Meath Park",
    "Medstead",
    "Medstead No. 497",
    "Meeting Lake No. 466",
    "Melfort",
    "Melville",
    "Melville Beach",
    "Mendham",
    "Meota",
    "Meota No. 468",
    "Mervin",
    "Mervin No. 499",
    "Metinota",
    "Michel Village",
    "Midale",
    "Middle Lake",
    "Milden",
    "Milden No. 286",
    "Milestone",
    "Milton No. 292",
    "Minton",
    "Miry Creek No. 229",
    "Mistatim",
    "Mistusinne",
    "Monet No. 257",
    "Montmartre",
    "Montmartre No. 126",
    "Montrose No. 315",
    "Moose Creek No. 33",
    "Moose Jaw",
    "Moose Jaw No. 161",
    "Moose Mountain No. 63",
    "Moose Range No. 486",
    "Moosomin",
    "Moosomin No. 121",
    "Morris No. 312",
    "Morse",
    "Morse No. 165",
    "Mortlach",
    "Mossbank",
    "Mount Hope No. 279",
    "Mount Pleasant No. 2",
    "Mountain View No. 318",
    "Muenster",
    "Naicam",
    "Neilburg",
    "Netherhill",
    "Neudorf",
    "Neville",
    "Newcombe No. 260",
    "Nipawin",
    "Nipawin No. 487",
    "Nokomis",
    "Norquay",
    "North Battleford",
    "North Battleford No. 437",
    "North Grove",
    "North Portal",
    "North Qu'Appelle No. 187",
    "Norton No. 69",
    "Oakdale No. 320",
    "Odessa",
    "Ogema",
    "Old Post No. 43",
    "Orkney No. 244",
    "Osage",
    "Osler",
    "Outlook",
    "Oxbow",
    "Paddockwood",
    "Paddockwood No. 520",
    "Pangman",
    "Paradise Hill",
    "Parkdale No. 498",
    "Parkside",
    "Patuanak",
    "Paynton",
    "Paynton No. 470",
    "Pebble Baye",
    "Pelican Narrows",
    "Pelican Pointe",
    "Pelly",
    "Pennant",
    "Pense",
    "Pense No. 160",
    "Perdue",
    "Perdue No. 346",
    "Piapot No. 110",
    "Pierceland",
    "Pilger",
    "Pilot Butte",
    "Pinehouse",
    "Pinto Creek No. 75",
    "Pittville No. 169",
    "Pleasant Valley No. 288",
    "Pleasantdale",
    "Pleasantdale No. 398",
    "Plenty",
    "Plunkett",
    "Ponass Lake No. 367",
    "Ponteix",
    "Poplar Valley No. 12",
    "Porcupine No. 395",
    "Porcupine Plain",
    "Prairie Rose No. 309",
    "Prairiedale No. 321",
    "Preeceville",
    "Preeceville No. 334",
    "Prelate",
    "Primate",
    "Prince Albert",
    "Prince Albert No. 461",
    "Progress No. 351",
    "Prud'homme",
    "Punnichy",
    "Qu'Appelle",
    "Quill Lake",
    "Quinton",
    "Radisson",
    "Radville",
    "Rama",
    "Raymore",
    "Reciprocity No. 32",
    "Redberry No. 435",
    "Redburn No. 130",
    "Redvers",
    "Reford No. 379",
    "Regina",
    "Regina Beach",
    "Reno No. 51",
    "Rhein",
    "Richard",
    "Richmound",
    "Ridgedale",
    "Riverhurst",
    "Riverside No. 168",
    "Rocanville",
    "Rocanville No. 151",
    "Roche Percée",
    "Rockglen",
    "Rodgers No. 133",
    "Rose Valley",
    "Rosedale No. 283",
    "Rosemount No. 378",
    "Rosetown",
    "Rosthern",
    "Rosthern No. 403",
    "Rouleau",
    "Round Hill No. 467",
    "Round Valley No. 410",
    "Ruddell",
    "Rudy No. 284",
    "Rush Lake",
    "Saltcoats",
    "Saltcoats No. 213",
    "Sandy Bay",
    "Sarnia No. 221",
    "Saskatchewan Beach",
    "Saskatchewan Landing No. 167",
    "Saskatoon",
    "Sasman No. 336",
    "Sceptre",
    "Scott",
    "Scott No. 98",
    "Sedley",
    "Semans",
    "Senlac",
    "Senlac No. 411",
    "Shamrock",
    "Shamrock No. 134",
    "Shaunavon",
    "Sheho",
    "Shell Lake",
    "Shellbrook",
    "Shellbrook No. 493",
    "Sherwood No. 159",
    "Shields",
    "Silton",
    "Silverwood No. 123",
    "Simpson",
    "Sintaluta",
    "Sliding Hills No. 273",
    "Smeaton",
    "Smiley",
    "Snipe Lake No. 259",
    "Souris Valley No. 7",
    "South Lake",
    "South Qu'Appelle No. 157",
    "Southey",
    "Spalding",
    "Spalding No. 368",
    "Speers",
    "Spiritwood",
    "Spiritwood No. 496",
    "Springside",
    "Spy Hill",
    "Spy Hill No. 152",
    "St. Andrews No. 287",
    "St. Benedict",
    "St. Brieux",
    "St. George's Hill",
    "St. Gregor",
    "St. Louis",
    "St. Louis No. 431",
    "St. Peter No. 369",
    "St. Philips No. 301",
    "St. Walburg",
    "Stanley No. 215",
    "Star City",
    "Star City No. 428",
    "Stenen",
    "Stewart Valley",
    "Stockholm",
    "Stonehenge No. 73",
    "Stony Rapids",
    "Storthoaks",
    "Storthoaks No. 31",
    "Stoughton",
    "Strasbourg",
    "Strongfield",
    "Sturgis",
    "Success",
    "Sun Valley",
    "Sunset Cove",
    "Surprise Valley No. 9",
    "Sutton No. 103",
    "Swift Current",
    "Swift Current No. 137",
    "Tantallon",
    "Tecumseh No. 65",
    "Terrell No. 101",
    "Tessier",
    "The Gap No. 39",
    "Theodore",
    "Thode",
    "Three Lakes No. 400",
    "Timber Bay",
    "Tisdale",
    "Tisdale No. 427",
    "Tobin Lake",
    "Togo",
    "Tompkins",
    "Torch River No. 488",
    "Torquay",
    "Touchwood No. 248",
    "Tramping Lake",
    "Tramping Lake No. 380",
    "Tribune",
    "Tugaske",
    "Tullymet No. 216",
    "Turnor Lake",
    "Turtle River No. 469",
    "Turtleford",
    "Tuxford",
    "Unity",
    "Usborne No. 310",
    "Val Marie",
    "Val Marie No. 17",
    "Valparaiso",
    "Vanguard",
    "Vanscoy",
    "Vanscoy No. 345",
    "Vibank",
    "Victory No. 226",
    "Viscount",
    "Viscount No. 341",
    "Vonda",
    "Wadena",
    "Wakaw",
    "Wakaw Lake",
    "Waldeck",
    "Waldheim",
    "Waldron",
    "Wallace No. 243",
    "Walpole No. 92",
    "Wapella",
    "Warman",
    "Waseca",
    "Watrous",
    "Watson",
    "Waverley No. 44",
    "Wawken No. 93",
    "Wawota",
    "Webb",
    "Webb No. 138",
    "Wee Too Beach",
    "Weekes",
    "Weirdale",
    "Weldon",
    "Wellington No. 97",
    "West End",
    "Weyakwin",
    "Weyburn",
    "Weyburn No. 67",
    "Wheatlands No. 163",
    "Whiska Creek No. 106",
    "White City",
    "White Fox",
    "White Valley No. 49",
    "Whitewood",
    "Wilcox",
    "Wilkie",
    "Willner No. 253",
    "Willow Bunch",
    "Willow Bunch No. 42",
    "Willow Creek No. 458",
    "Willowdale No. 153",
    "Wilton No. 472",
    "Windthorst",
    "Winslow No. 319",
    "Wise Creek No. 77",
    "Wiseton",
    "Wolseley",
    "Wolseley No. 155",
    "Wolverine No. 340",
    "Wood Creek No. 281",
    "Wood Mountain",
    "Wood River No. 74",
    "Wreford No. 280",
    "Wynyard",
    "Yarbo",
    "Yellow Grass",
    "Yorkton",
    "Young",
    "Zealandia",
    "Zelma",
    "Zenon Park",
    "Île-à-la-Crosse",
  ],
  YT: [
    "Beaver Creek",
    "Burwash Landing",
    "Carcross",
    "Carmacks",
    "Dawson",
    "Destruction Bay",
    "Faro",
    "Haines Junction",
    "Ibex Valley",
    "Johnsons Crossing",
    "Keno Hill",
    "Mayo",
    "Mt. Lorne",
    "Old Crow",
    "Pelly Crossing",
    "Ross River",
    "Stewart Crossing",
    "Swift River",
    "Tagish",
    "Teslin",
    "Upper Liard",
    "Watson Lake",
    "Whitehorse",
  ],
};

export function citiesForProvince(provinceCode: string): string[] {
  const code = (provinceCode || "").toUpperCase();
  return CA_CITIES_BY_PROVINCE[code] || [];
}

export function isKnownCity(provinceCode: string, city: string): boolean {
  const c = (city || "").trim();
  if (!c) return false;
  return citiesForProvince(provinceCode).some((x) => x.toLowerCase() === c.toLowerCase());
}

/** City options for a select, injecting a legacy value when not in the curated list. */
export function citySelectOptions(provinceCode: string, currentCity: string): string[] {
  const base = citiesForProvince(provinceCode);
  const cur = (currentCity || "").trim();
  if (!cur) return base;
  if (base.some((x) => x.toLowerCase() === cur.toLowerCase())) {
    // Prefer canonical casing from the list
    return base;
  }
  return [cur, ...base];
}
